### ISSUE TITLE
[Bug] Short Player is not affected by some tweaks anymore

### ISSUE THREAD

**Issue by craftgeil** [arichornlover/uYouEnhanced#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 17.0.3
- Device model: iPad (9. Generation) / iPhone SE 2020
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sideloadly
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): [v18.40.1-3.0.1 + uYouPlusExtra Features]

### Describe the bug

So I think YouTube updated their UI, and it broke some functionality for the Short Player.
So what I saw is that: 
1. The dislikes won't show
2. some uYou's Features do not work (e.g. "Hide Remix Button")

I do not know if you can fix these issues or if is a bigger problem with the uYou and iSponsorBlock Tweaks.

![IMG_0330](https://github.com/arichorn/uYouPlusExtra/assets/80261988/39785d84-a1b3-43b2-965e-4a0c57f339be)
![IMG_0332](https://github.com/arichorn/uYouPlusExtra/assets/80261988/3084b98b-f5b9-4342-9c62-6a013cee4b08)

### Steps to reproduce the issue

1. I do not know if everyone has the same UI, but if you have, check the Short Player.

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by craftgeil** [comment]
Thank you very much for the advice, setting the version to 18.20.3 worked perfectly. The remix button is hidden and the dislikes are once again shown.

**Comment by JACKKY04** [comment]
Having same sorta issue where I cannot hide Shorts cells.
