### ISSUE TITLE
[Bug] uYouPlus’ “Hide channel watermark” doesn’t do anything

### ISSUE THREAD

**Issue by pha1n0q** [arichornlover/uYouEnhanced#198]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: iOS 15.7.1
- Device model: iPhone 13
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sideloadly
- The specific version of uYouPlusExtra (**latest or newest is NOT a version number!**): v18.44.3-3.0.1-F2

### Describe the bug

The setting which should “Hide channel watermark[s]” under uYouPlus’ settings doesn’t appear to be working. This setting worked in the original uYouPlus’ .ipa compiled by qnblackhat ([v18.14.1-3.0](https://github.com/qnblackcat/uYouPlus/releases/tag/v18.14.1-3.0)), but not in uYouPlusExtra’s latest release ([v18.44.3-3.0.1-F2](https://github.com/arichorn/uYouPlusExtra/releases/tag/v18.44.3-3.0.1-F2)).

![4ECB7F7F-672A-4B05-8473-A424BF541696](https://github.com/arichorn/uYouPlusExtra/assets/88598340/c8f97034-56ad-4c5c-a33e-0fef7bdc9089)
![89F8D99E-3E26-4EF1-AD87-7467D21BC4CD](https://github.com/arichorn/uYouPlusExtra/assets/88598340/971b925d-7a74-489d-bbc3-ce6c7056db57)

### Steps to reproduce the issue

1. Open the YouTube in-app’s settings.
2. Navigate to `uYouPlus`
3. Navigate to `Video Controls Overlay Options`
4. Turn on the `Hide channel watermark` setting
5. Restart the YouTube app
6. Open a video from a channel that has a channel watermark (e.g. [Storyline EP "La vaguelette" MV | Genshin Impact](https://youtu.be/jHjUHKdoaqI))
7. View the video in full screen
8. Channel watermark is still there.

Video demonstration: https://www.youtube.com/watch?v=IWUSgtqwcec

### Crash log (if the app crashes)

```shell
App does not crash
```

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by Shaukariya** [comment]
Yh same

**Comment by HexCodeFFF** [comment]
Can still repro this issue on the latest version
![IMG_9656](https://github.com/arichorn/uYouPlusExtra/assets/35177464/afb01f5e-a70a-405e-9ed1-24f7a7b5b80e)
