### ISSUE TITLE
[Bug] All videos get 1.5x speed by default if YTSpeed is enabled

### ISSUE THREAD

**Issue by aaronliu0130** [arichornlover/uYouEnhanced#254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 17.1.1
- Device model: 14 Plus
- Sideload tool (AltStore, Sideloadly, TrollStore,...): SideStore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): [v18.49.3](https://github.com/arichorn/uYouEnhanced/releases/tag/v18.49.3-3.0.1)

### Describe the bug

If I have YTSpeed enabled, all videos will default to 1.5x speed.

### Steps to reproduce the issue

1. Enable YTSpeed
2. Restart app
3. Open any video

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by Cavonzio** [comment]
i have the same issue on iOS 16.6.1, but it defaults at 1.25 for me.
