### ISSUE TITLE
Button to select quality ?

### ISSUE THREAD

**Issue by louiscrc** [arichornlover/uYouEnhanced#289]
I used to have a version of the app where there was a way to get a button to select quality directly over the video player, instead of pressing settings-wheel>quality preferences>..., but I can't find it anymore in the settings of uYou now 🤨
Does it still exist ?

**Comment by louiscrc** [comment]
> Are you talking about the `YouQuality` tweak? If you want to use that go to `Settings > Video overlay`

The thing is there isn't anymore such a section in the settings, or at least not in mine...

**Comment by bhackel** [comment]
I see the feature in 19.01 and it is working, are you still having this problem? If not then I will go ahead and close this issue

**Comment by louiscrc** [comment]
> I see the feature in 19.01 and it is working, are you still having this problem? If not then I will go ahead and close this issue

I'm on 19.01 too and I still don't have anything... are you using a version spoofer to a particular version ? and is the button the "enable save to playlist button" option or elsewhere ?
