### ISSUE TITLE
[Bug] Failed to inject tweak in Bootstrap (i know its not useful much but)

### ISSUE THREAD

**Issue by dora727** [arichornlover/uYouEnhanced#291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

16.4

### Device model

iPhone SE 2022

### Sideload tool

TrollStore

### Tweak version

uYouEnhanced v19.01.1

### Describe the bug

![IMG_4996](https://github.com/arichornlover/uYouEnhanced/assets/109880918/33183c1f-69a9-4f11-bbbc-02d3c26bfa3d)

Enabling in AppEnabler got this error, even it enabled, when i open youtube it crashed

### Steps to reproduce the issue

1. install Bootstrap
2. Go to AppEnabler in Bootstrap
3. Enable YouTube

### Crash log (if the app crashes)

```shell
(unfortunately i cant find log)
```

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

might be useless for y’all, but i wanna use custom font in yt lol

**Comment by bhackel** [comment]
I don't have an iOS device on iOS 16 so I won't be able to debug this unfortunately.

**Comment by dora727** [comment]
So I found a solution, just update Bootstrap.
