### ISSUE TITLE
[Bug] 2560x1080p (1440p @ 21:9) does not appear with VP9 turned on

### ISSUE THREAD

**Issue by pha1n0q** [arichornlover/uYouEnhanced#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

iOS 15.7.1

### Device model

iPhone 13 MLN13LL/A

### Sideload tool

Sideloadly

### Tweak version

uYouEnhanced v19.01.1-3.0.1

### Describe the bug

A [video](https://www.youtube.com/watch?v=pzVbokRUyGU&list=PLeqzARGZ6F2IRIYzMJvuEK_1XKv4K-_cj&index=8) that is in the 21:9 aspect ratio at (what YouTube labels as) 1440p (2560x1080) is not an quality option with VP9 decoding turned on. This quality option is available on the official YouTube app as well as the [latest version](https://github.com/qnblackcat/uYouPlus/releases/tag/v18.14.1-3.0) of uYouPlus.

Official YouTube app: ![IMG_6748](https://github.com/arichornlover/uYouEnhanced/assets/88598340/61b3249a-7df5-4f71-98f0-1851e5c4bb61)

uYouEnhanced: ![IMG_6749](https://github.com/arichornlover/uYouEnhanced/assets/88598340/3b263e7c-4a66-4112-97e9-1156730fdb58)

I don't believe that this is an issue that occurs on other widescreen aspect ratios as this does not occur with a LinusTechTips [video](https://www.youtube.com/watch?v=jGMunhTa7Z8) with an aspect ratio of 1:2.

LinusTechTips video: ![IMG_6750](https://github.com/arichornlover/uYouEnhanced/assets/88598340/9b5ca23e-2f79-47ab-86c2-cd0b6847a516)

### Steps to reproduce the issue

1. Turn on VP9 decoding via Settings > Video quality preferences > Use VP9 `ON`
2. Open a video that has a 21:9 aspect ratio with a YouTube quality greater than 1080p (e.g. this [video])(https://www.youtube.com/watch?v=pzVbokRUyGU&list=PLeqzARGZ6F2IRIYzMJvuEK_1XKv4K-_cj&index=8)
3. Open the video quality settings panel

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by SuperAmirhamza** [comment]
![IMG_7375](https://github.com/arichornlover/uYouEnhanced/assets/45406543/5e117e14-e802-4597-b690-cdacb36a5bf6)
It’s showing there for me on latest version of uyouenhanced

**Comment by SuperAmirhamza** [comment]
Idea go on the uyou settings and in default video quality whatever the option is called select 1440p and try then

**Comment by SuperAmirhamza** [comment]
![image](https://github.com/arichornlover/uYouEnhanced/assets/45406543/9ca3c63a-8521-485e-b209-539828736076)
It's there for me. Go on the uyou settings and go to YT video quality and select 1440p

**Comment by bhackel** [comment]
Is it possible that Youtube doesn’t keep a VP9 encoded version at 1440p of this type of video on their servers? I am not too familiar with this feature

**Comment by gd82324976** [comment]
iOS 15.7.1(iPhone 13 Mini) me too, some video quality not appear whth VP9 turned on.

eg. https://youtu.be/9EajE9VzFKA

when VP9 turned off, there are 8 video quality options(2160p60 HDR, 1440p60 HDR, 1080p60 HDR, 720p60 HDR, 480p60 HDR, 360p60 HDR, 240p60 HDR, 144p60 HDR), when VP9 turned on, only 2 vedio quality options(2160p60 HDR, 1440p60 HDR).

**Comment by bhackel** [comment]
This might be related to https://github.com/MiRO92/uYou-for-YouTube/issues/356
