### ISSUE TITLE
No stock hold for 2x speed 

### ISSUE THREAD

**Issue by Luso02** [arichornlover/uYouEnhanced#297]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

I tried to disable all the related settings in the app, but I can't enable the stock hold for 2x speed, What can I do?

**Comment by Luso02** [comment]
I've already done this and it doesn't work. With the option off, when I hold, the "seek anywhere" feature appears, and not the stock hold for 2x

**Comment by bhackel** [comment]
It’s problem of switching between the stock 2x Speed feature and the stock Seek Anywhere gesture is up to Youtube to decide. However, the next version of uYouEnhanced should come with an updated version of Hold For Speed that allows you to switch between the two.

**Comment by JudeTheTechSavvyDude** [comment]
I hate the 2X Speed for sure it's gets annoying for sure, because it goes thru the video faster, and i absolutely hate it 1000%

**Comment by bhackel** [comment]
Yes that did inconsistently work for me, but if you can wait, I think @arichornlover will make a new release in a few days

**Comment by Luso02** [comment]
Than I guess I'll wait the next version thx a lot
