### ISSUE TITLE
Comments blank glitched in shorts

### ISSUE THREAD

**Issue by yodaluca23** [arichornlover/uYouEnhanced#318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

17.3

### Device model

iPhone 14 Pro

### Sideload tool

Sideloadly

### Tweak version

https://github.com/yodaluca23Alt/uYouEnhanced/releases/download/v19.03.2-3.0.1-%2833%29/uYouEnhanced_19.03.2_3.0.1.ipa

### Describe the bug

Comments are blank and glitched in shorts, on v19.03.2

### Steps to reproduce the issue

1. Build with YouTube version 19.03.2
2. Install
3. Open the app
4. Go to shorts tab
5. Press comments

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

Screenshots:
![IMG_5264](https://github.com/arichornlover/uYouEnhanced/assets/67206487/47b5217d-57bb-481f-bd57-6c5e9240380f)

**Comment by asdfzxcvbn** [comment]
can reproduce on youtube v19.04.3, iphone 12 pro, 16.2, TS2

**Comment by yodaluca23** [comment]
> I’m certain it was because I was attempting to modify `_ASDisplayView`?
> 
> https://github.com/arichornlover/uYouEnhanced/commit/eef213242c1aaabf6e35bded8dcbd0259bc4dce3
> 
> to remove gaps in the video player?
> 
> I didn’t expect it to effect everything else in the app?

Lol it's OK, is that also why (I was debating making new issue about this) the video descriptions are gone on the homepage and the thumbnails, are gone in the You tab..

**Comment by yodaluca23** [comment]
> I’m certain it was because I was attempting to modify `_ASDisplayView`?
> 
> https://github.com/arichornlover/uYouEnhanced/commit/eef213242c1aaabf6e35bded8dcbd0259bc4dce3
> 
> to remove gaps in the video player?
> 
> I didn’t expect it to effect everything else in the app?

Just rebuilt with the latest commit, can confirm all said bugs are fixed, thanks! Closing...
