### ISSUE TITLE
Hiding the uYouPlus Extra button leaves ugly gap.

### ISSUE THREAD

**Issue by theoccurrence** [arichornlover/uYouEnhanced#376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

16.4

### Device model

12 Pro Max

### Sideload tool

Trollstore

### Tweak version

v19.06.2-3.0.3 + uYouEnhanced Features

### Describe the bug

Title

### Steps to reproduce the issue

1. Hide uYou Plus Extra button
2. Enjoy the gap.

![IMG_0782](https://github.com/arichornlover/uYouEnhanced/assets/16444679/926a0df3-d833-49b1-865a-2cacc7e6d780)

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

None

**Comment by hi-im-karma** [comment]
Agree. It looked way better(cleaner) before:
![image](https://github.com/arichornlover/uYouEnhanced/assets/73917917/d0826d3e-29f6-4f4d-8f13-00e361c1181a)

**Comment by hi-im-karma** [comment]
I thought that new odd looking uyouplus button was an attempt to troll us

**Comment by Ketarmin** [comment]
> > I thought that new odd looking uyouplus button was an attempt to troll us
> 
> That button was just there to give anyone the ability to clear cache and being able to customize the colors just like YouTubeReborn / YouTubeRebornPlus. I did modify the button in the latest release **v19.07.5-3.0.3**


It looks like this for me now 

![IMG_5190](https://github.com/arichornlover/uYouEnhanced/assets/27588441/7f70b252-8111-4a73-b4f0-f4dd2323576f)

**Comment by Ketarmin** [comment]
> > ![IMG_5190](https://private-user-images.githubusercontent.com/27588441/307510020-7f70b252-8111-4a73-b4f0-f4dd2323576f.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3Njk1OTYsIm5iZiI6MTcwODc2OTI5NiwicGF0aCI6Ii8yNzU4ODQ0MS8zMDc1MTAwMjAtN2Y3MGIyNTItODExMS00YTczLWI0ZjAtZjRkZDIzMjM1NzZmLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQxMDA4MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDE1NjY0M2U3ZmU4ZWRjZTUxYzhlZTIxNDE4OWRhNjNjNzkzOTk1MzViOGUzMGU2YTY4Y2ZiYTAxYzNjY2JhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a0BPUBtO-LEL_w_r73m4jQdqxzJ_ykbTszOIRDUpkw0)
> 
> Dear gosh, I hate how it looks like that, should I change it to make it similar to the icon from the uYou Tab in the Pivot Bar?

unfortunately im not able to this your picture but i think it would be better to use a similar icon

**Comment by theoccurrence** [comment]
> Also was wondering if the gap was gone if attempting to hide the Button. I tried resizing the icon’s frame so it will leave no gap if the `Hide uYouPlus` option was enabled.

Yes, the gap is gone. I'm going to close this issue now.
