### ISSUE TITLE
[Bug] Autoplay doesn’t work

### ISSUE THREAD

**Issue by misa198** [arichornlover/uYouEnhanced#388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

iOS 17.0.2

### Device model

iPhone 11

### Sideload tool

Sideloadly

### Tweak version

v19.07.5-3.0.3 + uYouEnhanced Features

### Describe the bug

In the video player, after I toggle the autoplay switch, the function no longer works, it only works when playing playlists. i tried uninstalling and reinstalling, but the problem is not resolved.

[![Watch the video](https://i.imgur.com/CXvVRWF.mp4)](https://i.imgur.com/CXvVRWF.mp4)

### Steps to reproduce the issue

1. Toggle autoplay switch

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by bhackel** [comment]
I can confirm that this is happening. It reminds me of the feature that removes the Suggested Video popup in portrait mode, but it happens regardless of if this feature is enabled or not.

I checked using FLEX and found that YTMainAppVideoPlayerOverlayViewController.shouldShowAutonavEndscreen is returning NO even though the following 2 settings are disabled
Youtube Settings -> uYouEnhanced -> Hide Suggested Video
uYou Settings -> Video Player -> No Suggested Videos at The Video End

Something is hooking this function somewhere, I will look around. I'm going to try testing the vanilla uYou IPA to see if it also has this issue.

**Comment by bhackel** [comment]
I figured it out... you need to turn **ON** the uYou setting for No Suggested Videos at The Video End, which will **ENABLE** the suggested video popup, and allow autoplay to work again. Let me know if that fixes your issue

**Comment by misa198** [comment]
@bhackel Thank you. The autoplay is working.
