### ISSUE TITLE
Request: Disable remaining time feature

### ISSUE THREAD

**Issue by KarmaBeast** [arichornlover/uYouEnhanced#415]
I often find myself accidentally tapping on the videolength and accidentally displaying the remaining time (instead of current).
![image](https://github.com/arichornlover/uYouEnhanced/assets/73917917/5a57e275-58bd-4349-a971-e80130672849)

I hate this (-time) feature that was added by YouTube. Can you add an option to disable it? When tapping the time it shouldn't change to minus.

**Comment by hi-im-karma** [comment]
This is annoying big time. Please developers allow for disabling this stupid YouTube feature 🙏🏻

**Comment by KarmaBeast** [comment]
Any updates on this?

![image](https://github.com/arichornlover/uYouEnhanced/assets/73917917/9a059b1d-df6f-49ff-90d1-3528b3c851a5)

This is super annoying. @bhackel

**Comment by bhackel** [comment]
Merging in soon, doing 1 final test
