### ISSUE TITLE
Black screen when scrolling on launch

### ISSUE THREAD

**Issue by OmniiOMEGA** [arichornlover/uYouEnhanced#424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

17.4

### Device model

iPhone 15 Pro Max

### Sideload tool

AppDB

### Tweak version

v19.08.2-3.0.3-F2

### Describe the bug

When you launch YouTube enhanced it gives you a black screen and when scrolling it’s delayed on loading thumbnails..

### Steps to reproduce the issue

1. Open YouTube
2. Scroll
3. Black windows and no thumbnails appearing

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by timoz1705** [comment]
I have the same issue. 
iPhone 15 Pro, iOS 17.3.1

**Comment by OmniiOMEGA** [comment]
> I have the same issue. 
> 
> iPhone 15 Pro, iOS 17.3.1

Yeah man, the thumbnails are delayed

**Comment by GoranGostovic** [comment]
Same issue here

**Comment by TheTrueShadow** [comment]
If you own a PC and use YouTube enhancer they state that YouTube is trying to push a new UI now maybe it's a bug but it's definitely caused by YouTube, because now for me it's happening on every version that is new it's not the 3 latest anymore.

**Comment by OmniiOMEGA** [comment]
@TheTrueShadow & @paperclips629 
I've discovered the fix for the scrolling weird black / white screen on the home screen.

Turn on under Settings > uYouEnhanced:
Fix LowContrastMode

**Comment by OmniiOMEGA** [comment]
I find solution as mentioned above ;)
