### ISSUE TITLE
"MrBeastify" what is this?

### ISSUE THREAD

**Issue by KarmaBeast** [arichornlover/uYouEnhanced#426]
For the first time I noticed this setting MrBeastify. Upon googling what it does, I still don't understand..
![image](https://github.com/arichornlover/uYouEnhanced/assets/73917917/0f6c0d10-2197-407b-a279-bfa40977e4fb)

Can someone please explain?

**Comment by hi-im-karma** [comment]
Also I don't think this deserves its own setting. A single option. It should be placed somewhere else instead of this prominently.

**Comment by KingGamingYT** [comment]
It adds different images of Mr. Beast to every thumbnail in the app. That's all it does. Le funni.

**Comment by hi-im-karma** [comment]
Seems dumb af but ok

**Comment by theoccurrence** [comment]
> > > Seems dumb af but ok
> 
> > 
> 
> > Some people like it (imo all it does is inflate the app size), not my place to judge them
> 
> 
> 
> It only adds like 10MB+ I should’ve compressed them more. I’ll see if I can reduce the file size 😅

Does this even work for any of you? I tried turning it off and on but I don't see any Mr. Beasts

**Comment by yodaluca23** [comment]
> Does this even work for any of you? I tried turning it off and on but I don't see any Mr. Beasts

Doesn't work for me, no, also, it defaults to on, at least that's what the switch displays, and it shouldn't have its own section, it should be in uYouEnhanced, or general...

**Comment by yodaluca23** [comment]
> > Doesn't work for me, no, also, it defaults to on, at least that's what the switch displays, and it shouldn't have its own section, it should be in uYouEnhanced, or general...
> 
> 
> 
> I think it’s broken. I can remove it if y’all want me to.

I mean, it's an interesting concept if you could make it work...

**Comment by KarmaBeast** [comment]
> I can remove it if y’all want me to.

Yeah it'd be nice if you remove it. One less section in the settings means better overview for navigating our way there. Or at the very least move this weird (imho useless) tweak elsewhere 👌🏻

![image](https://github.com/arichornlover/uYouEnhanced/assets/73917917/603ea00f-d624-4955-93a7-edd5f064b88b)
