### ISSUE TITLE
Build and Release errors out, exit code 9

### ISSUE THREAD

**Issue by Kylesare57** [arichornlover/uYouEnhanced#436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

17.3.1

### Device model

iPhone 14 Pro

### Sideload tool

ipa not created 

### Tweak version

19.09.4-3.0.3

### Describe the bug

I have tried renaming the ipa to youtube.ipa YouTube.ipa, tried compressing it to youtube.zip and YouTube.zip but I get the same error every time. I have it set to share with anyone with the link

URL:https://drive.google.com/file/myfile-> "main/YouTube.ipa" [1]
[YouTube.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of YouTube.zip or
        YouTube.zip.zip, and cannot find YouTube.zip.ZIP, period.
Error: Process completed with exit code 9.

### Steps to reproduce the issue

1. enter url of ipa, I'm currently hosting on google drive 
2. run workflow

### Crash log (if the app crashes)

```shell
URL:https://drive.google.com/file/myfile-> "main/YouTube.ipa" [1]
[YouTube.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of YouTube.zip or
        YouTube.zip.zip, and cannot find YouTube.zip.ZIP, period.
Error: Process completed with exit code 9.
```

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by waz11** [comment]
can you send a link to the decrypted YouTube ipa?

**Comment by Kylesare57** [comment]
> @arichornlover can you share a link to the decrypted YouTube ipa? or maybe share the uYouPlus build ?

No sharing the YouTube ipa was the issue

**Comment by Kylesare57** [comment]
> > > @arichornlover can you share a link to the decrypted YouTube ipa? or maybe share the uYouPlus build ?
> > 
> > 
> > No sharing the YouTube ipa was the issue
> 
> You can share it. But I will most likely delete the url later today but I won’t delete it immediately.

For the decrypted ipa right? Not for the repository?

**Comment by Kylesare57** [comment]
I’ll probably close after you reply since changing to Dropbox solved the issue

**Comment by Kylesare57** [comment]
okay I'll assume you meant the spa since that makes the most sense, to reiterate the solution. Don't use google drive use another host, dropbox works and I've heard litter works as well, thanks for coming to my ted talk
