### ISSUE TITLE
[Bug] VP9 option is broken

### ISSUE THREAD

**Issue by gototheskinny** [arichornlover/uYouEnhanced#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version:15.0
- Device model:iphone 12
- Sideload tool: TrollStore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**):18.25

### Describe the bug

Vp9 enabling option is actually enables h264 not vp9.

### Steps to reproduce the issue

1. "Fresh install uses vp9"
2. Enable vp9 in the video quality settings
3. Now you have avc h264 at all times.

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by CSKnock** [comment]
Can confirm also happens here. Funny thing is that if you force VP9 qualities within uYou (like 1440p+) the app just immediately crashes upon tap. I had thought this was a bug because of a feature in uYou+ Extra but it’s related to the VP9 bug you’ve reported here.

**Comment by CSKnock** [comment]
> Can confirm also happens here. Funny thing is that if you force VP9 qualities within uYou (like 1440p+) the app just immediately crashes upon tap. I had thought this was a bug because of a feature in uYou+ Extra but it’s related to the VP9 bug you’ve reported here.

…never mind I guess. i did a fresh re-install of the ipa and it still doesn’t have VP9 working. i’ll downgrade to an older version for now

**Comment by bernie8026** [comment]
i find out that if i just enable the vp9 settings then i will have vp9 nothing goes wrong. but if i enable the uYou settings and set the video quality to 2160 and the app will crash.

**Comment by bernie8026** [comment]
> i find out that if i just enable the vp9 settings then i will have vp9 nothing goes wrong. but if i enable the uYou settings and set the video quality to 2160 and the app will crash.

and 1080p will use avc1 2160 will use vp9

**Comment by gototheskinny** [comment]
18.08.1 has this issue too BTW. This version overall has better stability.

**Comment by gototheskinny** [comment]
@arichornlover I don't use Trollstore anymore(jb swapped). sideloaded ipa doesn't have any issues anymore.
