### ISSUE TITLE
Error: Failed to inject uYouPlus.dylib into YouTube.app

### ISSUE THREAD

**Issue by EnRokuro** [arichornlover/uYouEnhanced#441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

iPadOS 17.4 (21E219)

### Device model

iPad Air 5 

### Sideload tool

Signulous

### Tweak version

v19.09.4-3.0.3

### Describe the bug

Stuck on [428 > Making stage for tweak uYouPlus…] for 1+ hr.

I also got about 14 [ld: warning: directory not found for option
'-F/Users/runner/work/uYouEnhanced/uYouEnhanced/main/.theos/obj/install/Library/Frameworks']

Eventually got [Error: Failed to inject uYouPlus.dylib into YouTube.app]

I used the previous uyou IPA instead of the original youtube IPA, maybe that's the problem?

### Steps to reproduce the issue

![Untitled](https://github.com/arichornlover/uYouEnhanced/assets/143202329/e8460b26-d160-4e10-8f05-436e3c195bb6)

### Are you using the newest version of uYouPlus? If not, why?

❌ No, I'll explain at the end of the template

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by EnRokuro** [comment]
omg, that finally worked. thx

**Comment by TiJean98** [comment]
Hi, i have the same issue, I don't understand what you did to fix it, can you explain me please?
