### ISSUE TITLE
Hide YouTube Premium sections

### ISSUE THREAD

**Issue by TheBeastMasterNL** [arichornlover/uYouEnhanced#445]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Can you please add a function to next further updates to hide the YouTube Premium sections? 
![IMG_5336](https://github.com/arichornlover/uYouEnhanced/assets/162719866/ebbda3ff-44be-4056-ac77-ac47c8d0c09a)
See picture below.

**Comment by Kylesare57** [comment]
what version of uYouEnhanced are you using?

**Comment by BeastGitHub17** [comment]
> what version of uYouEnhanced are you using?

The newest uYouEnhanced

**Comment by Kylesare57** [comment]
@arichornlover

**Comment by bhackel** [comment]
Where is this located? I think my You/Home page looks different… 😅 ![image](https://github.com/arichornlover/uYouEnhanced/assets/34104885/2111941e-d999-427d-8303-9065741677c6)

**Comment by BeastGitHub17** [comment]
> Where is this located? I think my You/Home page looks different… 😅 ![image](https://github.com/arichornlover/uYouEnhanced/assets/34104885/2111941e-d999-427d-8303-9065741677c6)

I see it already in your picture; Get YouTube Premium, but also the subscriptions tab is in my profile. If you have iPad layout you should see it in the bar under, You. Otherwise you should see your profile picture in the top right corner and then you should see the screen. Let me know please.

**Comment by bhackel** [comment]
I restarted my app and it magically appeared now. I will see if I can remove it ![image](https://github.com/arichornlover/uYouEnhanced/assets/34104885/a22c6815-5794-4d4d-ac4c-7ecf57c88cce)

**Comment by BeastGitHub17** [comment]
> I restarted my app and it magically appeared now. I will see if I can remove it ![image](https://github.com/arichornlover/uYouEnhanced/assets/34104885/a22c6815-5794-4d4d-ac4c-7ecf57c88cce)

Yeah, the app is bugging in iPhone and iPad layout sometimes, that's a bug I think. That would be very nice! Let me know!

**Comment by bhackel** [comment]
O yea that’s true, thanks

**Comment by BeastGitHub17** [comment]
> O yea that’s true, thanks

Have you by any chance found how to remove the YT Premium sections already?

**Comment by bhackel** [comment]
Still looking into it, it seems more difficult than I was expecting

**Comment by BeastGitHub17** [comment]
> Still looking into it, it seems more difficult than I was expecting

Can't you copy the codes from the hide account, try new features etc and change it to YouTube premium? Or am I wrong? If I need to test something, let me know

**Comment by bhackel** [comment]
Yeah I was looking at that code and there didn’t seem to be a similar way for the premium stuff unfortunately

**Comment by BeastGitHub17** [comment]
> Yeah I was looking at that code and there didn’t seem to be a similar way for the premium stuff unfortunately

Oh shit so it's not possible you think?

**Comment by bhackel** [comment]
I'll keep looking for now since there's likely a way

**Comment by BeastGitHub17** [comment]
> I'll keep looking for now since there's likely a way

Wait purchases and subscriptions is in the settings menu, same as try new features and account settings. So that code you can copy, that's in the same menu?

**Comment by bhackel** [comment]
Commits were merged in recently, this issue can be closed now.
