### ISSUE TITLE
Keep Remaining Time enabled across restarts

### ISSUE THREAD

**Issue by samuelawachie** [arichornlover/uYouEnhanced#448]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

When one sets the video player to show the remaining time rather than the elapsed time, it always resets after a restart of the application. I always personally prefer the remaining time to elapsed. And I want it to be enabled across restarts rather than having to set it each time.

**Comment by bhackel** [comment]
Can you check if this happens in the stock Youtube App? You can install both at the same time btw, which makes it easier to test.

**Comment by samuelawachie** [comment]
> Can you check if this happens in the stock Youtube App? You can install both at the same time btw, which makes it easier to test.

Yes, it happens that way in the original YouTube app. Does that mean this cannot be implemented? Coz this elapsed time thingy gets tedious fast having to do it every single time I open the app. I’ve done it over a million times now perhaps. 
It’s the first thing I change on any music/video player I use. Foobar, Spotify, VLC,SM player, you name it. All of them remember that setting though, except this YouTube app

**Comment by bhackel** [comment]
Ah okay, it should be easy to make. I will let you know in the next few days

**Comment by samuelawachie** [comment]
> Ah okay, it should be easy to make. I will let you know in the next few days

I’d have said “You’re my own personal Jesus Christ”.. but that would draw even more attention to the fact that you’re my Neo now 😍☺️
Can’t wait 🎉🥳

**Comment by bhackel** [comment]
Oh sorry, I thought I tested it working, but I will try again to see. It should be setting it to remaining time after an app restart. I will check

**Comment by samuelawachie** [comment]
There are some rare occasions that it worked. Once when i logged into my alternate account (rarely used; only used for football to escape them overrunning my main feed), it worked. When logged out of all accounts, it did work on 2 videos. On my main account, with lots of samples (opened about 30 different videos across watch-later, downloads, subscriptions) it didn't work.
So it's rare but for it does work for those exceptions showing that the code "can" work and perhaps there's a logic error somewhere, making it not work in all (or most) cases.

**Comment by samuelawachie** [comment]
> Oh sorry, I thought I tested it working, but I will try again to see. It should be setting it to remaining time after an app restart. I will check

I wonder if any more progress has been made on this?
