### ISSUE TITLE
stuck in "Fix compiling & Build Package" when I building with Github Actions

### ISSUE THREAD

**Issue by okkkkoo** [arichornlover/uYouEnhanced#456]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

 ❌ No, I don't think this is a bug. I will explain below

### My question

Just like what title say
![image](https://github.com/arichornlover/uYouEnhanced/assets/77115336/a3c2d7df-44b0-40b6-8356-8ac08d0fad39)

**Comment by okkkkoo** [comment]
![image](https://github.com/arichornlover/uYouEnhanced/assets/77115336/e6eb7089-6f36-4fd8-8254-ff037b11e2f2)
I'm using uYouEnhanced_19.07.5-3.0.3.ipa. Is that okay?

**Comment by okkkkoo** [comment]
![image](https://github.com/arichornlover/uYouEnhanced/assets/77115336/b9a7dae7-016b-4ada-9c98-681b607409ed)
![image](https://github.com/arichornlover/uYouEnhanced/assets/77115336/a9a1b545-c800-4bb1-a998-daf5891f811e)
still experiencing the same issues.

**Comment by okkkkoo** [comment]
when I change an ipa,the problem is solved

**Comment by stefanolozito** [comment]
> when I change an ipa,the problem is solved

Tried with different YouTube ipas and having the same issue. What ipa did you use?
