### ISSUE TITLE
[Bug] Home screen appears blank due to ads not getting properly blocked

### ISSUE THREAD

**Issue by paulxh** [arichornlover/uYouEnhanced#457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

17.4

### Device model

15 Pro

### Sideload tool

SideStore

### Tweak version

v19.10.5-3.0.3

### Describe the bug

As per https://www.reddit.com/r/sideloaded/comments/1bfh3yg/anyone_else_getting_a_blank_home_page_in_uyou/
![WhatsApp Image 2024-03-16 at 22 44 45](https://github.com/arichornlover/uYouEnhanced/assets/26500893/d80e855c-9607-4def-aae5-3b1c2ef5d6fe)
Whenever I open the app and only for my account (trying offline or using other accounts works), the home page appears black.

If I scroll down, some videos start to appear then disappear again and so on.

Disabling the adblock on the home page through the associated setting makes the home page load correctly (although now the ads are present).

It seems only some users are having this issue and I'm not sure what to do.
I've tried different youtube tweaks and all of them seem to have the same problem for my specific account.

### Steps to reproduce the issue

1. Log in to account
2. Enter home page
3. See that the home page is not displayed correctly

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by paulxh** [comment]
Actually, this is most probably a uYou issue, probably should have thought of that since I tried different tweaks that are all based on uYou.

Found this related issue on the uYou GitLab repo: https://github.com/MiRO92/uYou-for-YouTube/issues/427

Will close tentatively in the meantime.

**Comment by advicepyro** [comment]
Chiming in to say this option doesn't work since this weekend. I toggled it off for now to get the feed to not look broken.
