### ISSUE TITLE
[Questions] Could you add a guide to build the IPA using the iPhone?

### ISSUE THREAD

**Issue by romantra** [arichornlover/uYouEnhanced#472]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

Can you add a guide to build the IPA using the iPhone? I'm using esign using developer certificate so would be great to learn how to build the IPA file from esign directly, so Thabks in advance!

**Comment by bhackel** [comment]
Consider joining the unofficial telegram group: https://t.me/uYouEnhanced Someone made a guide on here for how to build with mobile. You have to turn your phone into landscape on the Github website (not app) to get the options available.
