### ISSUE TITLE
[Feature Request] Give back recommendations on home page

### ISSUE THREAD

**Issue by yodaluca23** [arichornlover/uYouEnhanced#473]
The home page is absolutely garbage now, it's full of only trending crap that is of no interest to me at all, and can't even find where to go to my recommended, it's probably an A/B flag somewhere, so should be easy to implement...

![image](https://github.com/arichornlover/uYouEnhanced/assets/67206487/6ec78c81-0061-4356-bb63-53b407228055)
All of the above is "Trending" I don't give a crap what kind of brain rot other people are watching. Please find this A/B flag and tell me what it is and add an option to revert it!

My A/B flags:
https://pastebin.com/aPMkTiBG

**Comment by bhackel** [comment]
That is very strange, can you verify that you are signed in and that you have not cleared your watch history recently? I’ll look through A/B flags if that’s the case then.

**Comment by yodaluca23** [comment]
> That is very strange, can you verify that you are signed in and that you have not cleared your watch history recently? I’ll look through A/B flags if that’s the case then.

I'm definitely signed in, and it happens, even when I switch accounts. I have lots of watch history, mostly shorts, but theirs a lot of long form too.

**Comment by yodaluca23** [comment]
@bhackel I completely reset my A/B, can u send me yours then I can compare and find if it's an A/B flag?

**Comment by bhackel** [comment]
Yes I can, currently having issues with copying to clipboard but I will send it soon

**Comment by bhackel** [comment]
Looks like AB Copy is crashing on 19.16, so I got this from 19.06.2
https://gist.github.com/bhackel/08ff070ee3cfffae3c0caa287808764a

**Comment by yodaluca23** [comment]
Figured it out! YouTube definitely must've changed something because this setting did not use to do this but if you change default start up page in uYou settings to explore you get this changing it to default which is what I've done put it back to how it used to be so I guess this is a new experimental explorer page Garbage...

![image](https://github.com/arichornlover/uYouEnhanced/assets/67206487/7dd1409a-7329-4b94-a782-97309a2ca516)

**Comment by bhackel** [comment]
Ah that is very weird. Good to see that it is solved
