### ISSUE TITLE
[Bug] Red Progress Bar doesn't work

### ISSUE THREAD

**Issue by xhfpsxm** [arichornlover/uYouEnhanced#490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

iOS 17.0

### Device model

xs max

### Sideload tool

SideStore

### Tweak version

uYouEnhanced 19.10.7-3.0.3

### Describe the bug

Red Progress Bar doesn't work.

### Steps to reproduce the issue

1. Turn on the red progress bar option.
2. Reboot.
3. Play the videos.
![IMG_0321](https://github.com/arichornlover/uYouEnhanced/assets/60850613/16705e96-d6e3-4252-a340-75ba86995020)

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by rklol237** [comment]
Settings > uYouEnhanced > Enable "Red progress bar"

**Comment by eduedp** [comment]
It's also not working on latest original uYouPlus

**Comment by bhackel** [comment]
@arichornlover I am busy for the next couple days, but there is a new implementation of Red Progress Bar in uYouPlus that we can use here

**Comment by bhackel** [comment]
I believe this is fixed, so I am going to close the issue now
