### ISSUE TITLE
Not a bug but a fix to the SponsorBlock problem

### ISSUE THREAD

**Issue by Ionutovic** [arichornlover/uYouEnhanced#491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

17

### Device model

14 pro max

### Sideload tool

Altstore

### Tweak version

19.8.2 3.0.3

### Describe the bug

Hi everyone! I’ve managed to find a fix so the SponsorBlock works on the latest version:

Disable SponsorBlock exit the YouTube app, go back to the YouTube app and play any video and while is playing swipe the video down so it goes in the MiniPlayer mode at the bottom of the screen tap the SponsorBlock icon at the top right corner of the screen and enable sponsorblock again, exit the YouTube  app and voila SponsorBlock is working again. 
If after doing all these steps the SponsorBlock doesn’t show up in the seek bar just exit the app couple of times and it should work like a charm.
I hope this works for everyone as it worked for me :) 

### Steps to reproduce the issue

1. App crashing when SponsorBlock enabled

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by ANTONBORODA** [comment]
Doesn't work for me

**Comment by Ionutovic** [comment]
> Doesn't work for me

Does the app still crashes?

**Comment by ANTONBORODA** [comment]
> > Doesn't work for me
> 
> Does the app still crashes? what version are you using? I’m one uYouEnhanced 3.0.3

Yep. Still crashed when opening any video.

**Comment by rklol237** [comment]
Sorry, still doesn't fix it.
Thanks for trying to be helpful though.

**Comment by dadiy** [comment]
Didnt work for me.

There is a workaround posted on isponsorblocks issues - https://github.com/Galactic-Dev/iSponsorBlock/issues/110#issuecomment-2024419710

Seems like version 18 of the YouTube app is not currently effected.

**Comment by JudeTheTechSavvyDude** [comment]
Have u tried Enabled the App Version Spoofer and chose the version 18.18.2 on the version of uYouEnhanced you were originally using before you installed 18.49.3_3.0.1, that is what fixed it for me

**Comment by dadiy** [comment]
> Have u tried Enabled the App Version Spoofer and chose the version 18.18.2 on the version of uYouEnhanced you were originally using before you installed 18.49.3_3.0.1, that is what fixed it for me, with keeping the iSponsorBlock on

I tried that and it still crashes for me with the spoofer set to 18.18.2 but it seems any spoofed version after 18.43 does work.

**Comment by rklol237** [comment]
I've turned on the YouTube version spoofer, selected the latest version, and SponsorBlock seems to be working and not crashing anymore!
