### ISSUE TITLE
iSponsorBlock is fixed apparently 

### ISSUE THREAD

**Issue by Excremation** [arichornlover/uYouEnhanced#493]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Sorry it’s not a question but according to this comment iSponsorBlock has been fixed:
 
 https://github.com/Galactic-Dev/iSponsorBlock/issues/110#issuecomment-2025908542

Are you able to test this? I’d try myself but I’ve no idea how

**Comment by idontevenknoww** [comment]
iSponsorBlock seems to work for me now on v3.0.3

**Comment by Excremation** [comment]
> https://github.com/arichornlover/uYouEnhanced/actions/runs/8486667354
> download the zip and it’ll contain an ipa. However this URL will get automatically removed soon so I won’t get into legal trouble with Google.

Thank you, but I installed it and it still doesn’t work :(

**Comment by Excremation** [comment]
> https://github.com/arichornlover/uYouEnhanced/actions/runs/8486667354
> download the zip and it’ll contain an ipa. However this URL will get automatically removed soon so I won’t get into legal trouble with Google.

Okay update, I just opened the app and it now works for some reason. All of my uYou settings were reset and had to be reconfigured but it now works. No idea what’s happened but thank you!

**Comment by Kylesare57** [comment]
> https://github.com/arichornlover/uYouEnhanced/actions/runs/8486667354 download the zip and it’ll contain an ipa. However this URL will get automatically removed soon so I won’t get into legal trouble with Google.
I assumed you knew, but you do know your iPas are still public on GitHub right?

**Comment by Kylesare57** [comment]
Isponsorblock never stopped working for me, weird

**Comment by Excremation** [comment]
> https://github.com/arichornlover/uYouEnhanced/actions/runs/8486667354
> download the zip and it’ll contain an ipa. However this URL will get automatically removed soon so I won’t get into legal trouble with Google.

Okay further update, sorry for being a nuisance… iSponsorBlock is on, but it’s behaving as if it’s off, which is why my app is working. It is not skipping any sponsored segments or even identifying them in videos :/
