### ISSUE TITLE
[Bug] Open In YouTube Safari Extension doesn't work

### ISSUE THREAD

**Issue by QuanTrieuPCYT** [arichornlover/uYouEnhanced#495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [x] Yes, I did read the FAQ

### iOS/iPadOS version

17.4.1

### Device model

iPhone 14 Plus (iPhone14,8)

### Sideload tool

Sideloadly

### Tweak version

uYouEnhanced v19.10.7-3.0.3

### Describe the bug

The title is completely self-explanatory.

When you go to a video on YouTube on Safari, the "Open in YouTube" popup showed up, clicking on it redirects to uYouEnhanced but the app just doesn't seem to do anything.

### Steps to reproduce the issue

1. Go to a YouTube Video on Safari
2. When the "Open in YouTube" popup appears, click Open
3. uYouEnhanced will launch but it will not do anything, even when you leave it open in the app switcher before

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by bhackel** [comment]
Current workaround is to press the share button in the youtube webpage in safari and open the link in youtube.

**Comment by QuanTrieuPCYT** [comment]
Seems to be fixed on my end after updating to the latest GitHub Actions build and iOS 17.5 Developer Beta 1. Closing this issue.
