### ISSUE TITLE
[v19.10.5-4.2.6] App Crash

### ISSUE THREAD

**Issue by JD9871** [arichornlover/uYouEnhanced#507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

17.5

### Device model

13 Pro Max

### Sideload tool

Signulous

### Tweak version

Youtube reborn plus v 19.10.5-4.2.6

### Describe the bug

Changing any setting in the app settings or tweaks causes instant crash on video. When you don’t mess with any settings it works perfect, but if you change anything all videos crash the app. No error just closes out.

### Steps to reproduce the issue

1. Open settings change any setting
2. Close then reopen
3. Pick any video then automatic crash

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by chasetb** [comment]
> Turn off iSponsorBlock, it’s usually the cause for the crashing.

Had the same issue and turning off iSponsorBlock fixed it. Thanks!

**Comment by ronmount** [comment]
> Also I think there a workaround to fix the crashing thanks to PoomSmart. there is a A/B flag called `enableModularPlayerBarController` turn this off?

I disabled this flag and it started works fine, thanks!

**Comment by oomek** [comment]
> Also I think there a workaround to fix the crashing thanks to PoomSmart.
> there is a A/B flag called `enableModularPlayerBarController` turn this off?

Thank you. It stopped crashing for me too when I disabled this flag.

**Comment by oomek** [comment]
Update. Disabling the flag only works temporarily. YT still crashes on playing a video when the system closes the app, or I force close it myself.

**Comment by UltraViolet37** [comment]
Wow — this tweak fixed not just the app crash, but also the failure to load every single video's meta data until specifically requested (and hence the ability for playlists to run unattended)

Thanks so much Arichorn!  ^-^  <3

**Comment by S1X0N3F0UR** [comment]
I disabled the flag & sponsor block, still crashes when I try to play a video. 🤦🏻‍♂️

**Comment by QuarterSwede** [comment]
> Wow — this tweak fixed not just the app crash, but also the failure to load every single video's meta data until specifically requested (and hence the ability for playlists to run unattended)
> 
> Thanks so much Arichorn! ^-^ <3
> 
> Edit: I sadly am now having the same issue as oomek. I fixed it by disabling the A/B flag but don't see how to disable SponsorBlock.

From the bottom YouTube Home tab look at the top of the app, there is an icon of a shield with a gear inside it. That’s iSponsorBlock settings. Tap on that and then Enabled.

**Comment by oomek** [comment]
iSpondorBlock still crashing Youtube in v19.14.2-3.0.3

**Comment by yodaluca23** [comment]
This is happening to me too, on long form videos, even with sponsor block disabled, and enableModularPlayerBarController disabled... YT: 19.14.3 Commit: 853e5a1a1049397b7c3171285d96f34eb2a16aa3

**Comment by yodaluca23** [comment]
@arichornlover A pr to uYou+ may have fixed this, https://github.com/qnblackcat/uYouPlus/pull/1428 could we get a sync?

**Comment by oomek** [comment]
Can confirm. v19.16.3-3.0.3 Is working with isponsorblock enabled.
