### ISSUE TITLE
[Bug] “Hide Fullscreen Button” Option breaks YouQuality Button in Video Player

### ISSUE THREAD

**Issue by arichornlover** [arichornlover/uYouEnhanced#511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

17.4.1

### Device model

10.5 iPad Pro (2017)

### Sideload tool

AltStore

### Tweak version

uYouEnhanced v19.13.1-3.0.3

### Describe the bug

When enabling the “Hide Fullscreen Button” Option you will most likely encounter a problem with the YouQuality tweak by PoomSmart when the Button is set to `Bottom`.

### Steps to reproduce the issue

1. turn on `YouQuality` and set the button to `Bottom` while `Hide Fullscreen Button` is enabled
2. 
3. 

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by KarmaBeast** [comment]
You mean this? Works fine for me

![image](https://github.com/arichornlover/uYouEnhanced/assets/73917917/645b7ef2-21e3-4d68-8fac-850505bcfdd4)

![image](https://github.com/arichornlover/uYouEnhanced/assets/73917917/ff725917-ee29-49a2-aece-e71a0dd4ee0e)

**Comment by KarmaBeast** [comment]
Which version do you want me to try? I can test later. (Only worried lately that ill loose 4K and VP9)

**Comment by KarmaBeast** [comment]
I updated to 19.13.1 and now also facing the same issue. It doesn't show at the bottom, but placing it at the top works. 

However like you, I very much prefer the quality button at the bottom :/ 

![image](https://github.com/arichornlover/uYouEnhanced/assets/73917917/1d94594d-1011-428d-8dfa-fcd0ef39457e)

I guess this needs a fix to work again with the hide fullscreen button tweak!

**Comment by KarmaBeast** [comment]
Also on vertical videos it's barely visible. Usually it would be next to the mute button at the bottom.

![image](https://github.com/arichornlover/uYouEnhanced/assets/73917917/3dea1a21-b1f9-4c7d-b870-0fed365b7103)

**Comment by KarmaBeast** [comment]
@arichornlover Any update on this? Can we make it work to have the quality button at the bottom again next to to the mute button? Like before

**Comment by KarmaBeast** [comment]
> Nope, but I’ll make it so that it turns off the YouQuality Button at the bottom in the video player instead.

What you mean? Currently it's hidden anyway when you choose bottom as location

**Comment by KarmaBeast** [comment]
Quality button at the top sucks. Would be so nice to have it at the bottom again. Just like it was before. Next to the mute button.

**Comment by bhackel** [comment]
Fixed by @arichornlover by reverting to an older version of YouQuality
