### ISSUE TITLE
[v19.12.3-3.0.3] Issue with Casting and Local Network

### ISSUE THREAD

**Issue by timfea926** [arichornlover/uYouEnhanced#514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

17.4.1

### Device model

iPhone 13

### Sideload tool

ESign 

### Tweak version

UYouEnhanced 19.12.3-3.0.3

### Describe the bug

When I click the Cast icon it tells me to go to Settings and enable Local Network access. The thing is Local Network is already enabled! This seems to be a problem across all tweaked YT apps.
![IMG_4390](https://github.com/arichornlover/uYouEnhanced/assets/50429353/73400534-4a40-48bf-9287-232e5ccb1d07)

### Steps to reproduce the issue

1. Open UYouEnhanced v19.12.3-3.0.3
2. Click the Cast icon at the top
3. When the prompt shows up Enable Local Network Access, open the Settings app and click YouTube to confirm that Local Network is in fact checked off
4. With Local Network enabled, close uYouPlus and restart, then try clicking the Cast icon again. If you have my problem, you will continue to get the same prompt to enable local network access even though you’ve already done so.

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

Same issue as all the other Tweaked YT apps.

**Comment by HyPeRXKo** [comment]
Can confirm, using an iphone 12/altstore, same problem.

**Comment by senorYME** [comment]
Yep doesn't work for me either , this is YouTube side sadly not our app

**Comment by sfksuperman** [comment]
arichornlover hasn't yet released version **`UYouEnhanced 19.12.3-3.0.3`**

**Comment by Write** [comment]
> arichornlover hasn't yet released version **`UYouEnhanced 19.12.3-3.0.3`**

They won't ever release again the IPA file you now have to build it yourself because of Google. 


I can confirm the issue still present with v19.3.1

**Comment by IphoneCake** [comment]
I had the same bug. I was able to work around it with a workaround by simply turning off the WLAN and then pressing the cast function again. If you have an Alexa Fire TV Stick or Cube, it should also be found, even if you are not connected to the Wi-Fi. Now press connect and you can stream via your smartphone again. However, this only works as long as the stick or Cube has power and remains switched on. If you disconnect the device from the power supply, simply repeat the steps.
I would be very grateful for a fix from Miro or arichornlover
 
Kind regards 
Dominik

**Comment by Write** [comment]
> I had the same bug. I was able to work around it with a workaround by simply turning off the WLAN and then pressing the cast function again. If you have an Alexa Fire TV Stick or Cube, it should also be found, even if you are not connected to the Wi-Fi. Now press connect and you can stream via your smartphone again. However, this only works as long as the stick or Cube has power and remains switched on. If you disconnect the device from the power supply, simply repeat the steps.
> 
> I would be very grateful for a fix from Miro or arichornlover
> 
>  
> 
> Kind regards 
> 
> Dominik 
> 
> 
> 
> 

While the menu indeed does show up again when wifi is turned off, it won't disocver my chromecast w m/ Google tv.

I tried to workaround this issue by linking the TV to the phone, via a code, which make the YouTube app controllable via Internet. Unfortunately I couldn't make it work once the YouTube app is closed. So it doesn't work the same as the cast option.

**Comment by Blockr22** [comment]
Still doesn’t work on the latest version of uyou enhanced that released today. Casting was working fine before

**Comment by Cynric10** [comment]
Same for me here. Worked fine for months and without any app change, just stopped working.

**Comment by IphoneCake** [comment]
Yes, the same applies to me. I use the uyouEnhanced [v19.02.1-3.0.1]
The uyouEnhanced version should have been released around the date 01.18.2024. 
I had updated to 3.0.3 [v19.10.5-3.0.3](https://github.com/arichornlover/uYouEnhanced/releases/tag/v19.10.5-3.0.3) recently, because I wanted to update again and only had problems. Sponsor block no longer worked, app kept crashing, so hardly usable. That was about a month ago. I then installed uyouEnhanced [v19.02.1-3.0.1] Version again via sideload, everything worked again as before, no problems. This also lasted for about 1 month.
Until recently the update 17.4.1 was installed via Itunes, because I wanted to make a backup of my IPhone 14 Pro Max. 
Then the massive casting problems started. 
As the previous speakers have already said, turn off WIFI and do it via cellular. It is best to connect to the TV beforehand using a manual code with the iPhone. I currently use a Fire TV Cube from Amazon with the "Smarttube" application. It should definitely work with this interaction. 
I would be interested to know, which IOS versions you have installed or whether it really is a Google problem, as older versions of uyouEnhanced are also affected by the problem. 

Kind regards 
Dominik

**Comment by timfea926** [comment]
Problem still looming. While I can confirm it works if wifi is off, I don’t like using my mobile data. I also rely on Chromecast 2 at home, which doesn’t give me the option to generate codes that I can use to connect the app with my tv. This has been quite a frustrating problem and I wish someone would try to find a solution.

**Comment by Write** [comment]
> Problem still looming. While I can confirm it works if wifi is off, I don’t like using my mobile data. I also rely on Chromecast 2 at home, which doesn’t give me the option to generate codes that I can use to connect the app with my tv. This has been quite a frustrating problem and I wish someone would try to find a solution. 

Honestly I don't have the problem anymore after playing around with A/B settings but I can't exactly remember what I changed besides

Edit : Well it seems there's an option to show all changes I made so here it is. 
Not sure what exactly is required or not.

Total: 9
YTColdConfig.clientInfraClientConfigEnableIosLocalPlaybackSequence2: 1
YTColdConfig.cxClientEnableIosLocalNetworkPermissionReliabilityFixes: 1
YTColdConfig.cxClientEnableIosLocalNetworkPermissionUsingSockets: 0
YTColdConfig.cxClientFallbackToLocalInitialPlaybackDescriptor: 1
YTColdConfig.cxClientSaveCloudScreenInfoInLocalStorageForSmoothPairingOnVerticals: 0
YTColdConfig.enableIosLocalPlaybackSequence: 0
YTColdConfig.isLocalTransportEncryptionEnabled: 1
YTHotConfig.deviceContextOnlySendOnWifi: 1
YTHotConfig.isPromptForLocalNetworkPermissionsEnabled: 0

**Comment by timfea926** [comment]
@Write Joffrey, you solved the problem!!! Thank you! (I typically don’t like people named Joffrey, but you are awesome ;))

**Comment by timfea926** [comment]
Joffrey provided the solution. Make sure to enable A/B settings and use the exact same permissions as below:

total:%209%0AYTColdConfig.clientInfraClientConfigEnableIosLocalPlaybackSequence2%3A%201%0AYTColdConfig.cxClientEnableIosLocalNetworkPermissionReliabilityFixes%3A%201%0AYTColdConfig.cxClientEnableIosLocalNetworkPermissionUsingSockets%3A%200%0AYTColdConfig.cxClientFallbackToLocalInitialPlaybackDescriptor%3A%201%0AYTColdConfig.cxClientSaveCloudScreenInfoInLocalStorageForSmoothPairingOnVerticals%3A%200%0AYTColdConfig.enableIosLocalPlaybackSequence%3A%200%0AYTColdConfig.isLocalTransportEncryptionEnabled%3A%201%0AYTHotConfig.deviceContextOnlySendOnWifi%3A%201%0AYTHotConfig.isPromptForLocalNetworkPermissionsEnabled%3A%200

**Comment by IphoneCake** [comment]
Did not solve the problem for me. I have adopted all the settings from Joffrey....

**Comment by Blockr22** [comment]
@YabberWalkie i don’t have ytcold or ythotconfig showing in A/B settings

**Comment by Blockr22** [comment]
Thank you very much, now the casting works like normal

**Comment by timfea926** [comment]
Not sure if I should reopen this issue or create a new one, but the problem is back and is applies to all older versions as of 19.19.5.

**Comment by ghstrida** [comment]
Can someone please help me understand what A/B settings are and where do I find them?
