### ISSUE TITLE
[v18.49.3-3.0.1] Hold for Speed is always on

### ISSUE THREAD

**Issue by ZeUseless** [arichornlover/uYouEnhanced#517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

17.3.1

### Device model

iPhone 13

### Sideload tool

Altstore

### Tweak version

18.49.3-3.0.1

### Describe the bug

![IMG_2768](https://github.com/arichornlover/uYouEnhanced/assets/67296134/d702049e-0ea2-4cf3-828d-7242b634d0da)
![IMG_2769](https://github.com/arichornlover/uYouEnhanced/assets/67296134/f5ced937-9066-41a5-8b98-ab05526d6952)

Hold for Speed is on even though I have it deselected in the setting. I have tried toggling everything off, including haptic, and then restart the app, but hold for speed is still on. 

### Steps to reproduce the issue

1. Turn Hold for Speed option all off
2. Open a video
3. Hold on the video while video is playing

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

Thank you for updating and maintaining this tweak!

**Comment by bhackel** [comment]
You may also be looking for the setting in uYouEnhanced -> Bring back the slide to seek gesture

Youtube added a stock Hold for 2X Speed gesture, which is the one that you are seeing. It is different than the tweak Hold For Speed.
