### ISSUE TITLE
[Bug] Premium logo is brocken 

### ISSUE THREAD

**Issue by Cagecellag** [arichornlover/uYouEnhanced#546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

17.3.1

### Device model

iPhone SE 2020

### Sideload tool

FlekSt0re

### Tweak version

uYouEnhanced 19.14.3-3.0.3

### Describe the bug

so after turning it on and restarting the app it works but when i restart it again it just turns it self off

### Steps to reproduce the issue

1. Turn on "YouTube premium logo"
2. Restart app
3. Restart app a second time

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by KarmaBeast** [comment]
Why the hell do you care about some useless logo?

**Comment by Cagecellag** [comment]
> Why the hell do you care about some useless logo? (If you want it so badly get YouTube Premium)

its a feature that was developed and it doesn't work, damn

**Comment by KarmaBeast** [comment]
> who even pays for that yt premium shit anyway 

https://www.theverge.com/2024/2/1/24058265/youtube-premium-music-100-million-subscribers

100 million people pay for it including myself.

Instead of requesting dumb useless shit such as a "Premium logo" that you can unlock yourself, how about you request useful features.

**Comment by Cagecellag** [comment]
> > who even pays for that yt premium shit anyway
> 
> https://www.theverge.com/2024/2/1/24058265/youtube-premium-music-100-million-subscribers
> 
> **100 million people** pay for it including myself.
> 
> Instead of requesting dumb useless shit such as a "Premium logo" that you can unlock yourself, how about you request useful features.

chill i reported a bug, thats all

**Comment by bhackel** [comment]
Is there an animated logo when you restart

**Comment by Cagecellag** [comment]
> Is there an animated logo when you restart

no its just this 
![IMG_9196](https://github.com/arichornlover/uYouEnhanced/assets/143967084/ef0932c7-e9e1-41df-a398-b46c78f5962c)

**Comment by bhackel** [comment]
Sorry I meant like is the Premium logo in the top left become an animated Youtube logo or is it just broken. Sometimes Youtube has the animated logos and I think it might cause  it to break

**Comment by Cagecellag** [comment]
> Sorry I meant like is the Premium logo in the top left become an animated Youtube logo or is it just broken. Sometimes Youtube has the animated logos and I think it might cause it to break

i never seen the logo animated so idk

**Comment by bhackel** [comment]
So I found out that it seems to work when the Yoodle is not active, which is the weird animation that replaces the logo. Will look into it soon

**Comment by yodaluca23** [comment]
I don't know what the issue yall having but it used to not work for the long time then I'm pretty sure @bhackel made a commit fixing it, and after that it was working on the later versions because I think before you had to spoof for it to work, which would get rid of the animated startup animation.

Is Yoodle like Google doodle for YouTube? Where it changes the logo for like holiday or something?

**Comment by bhackel** [comment]
Yep, I'm not sure the exact name but I saw that while digging through the class properties, and I thought it might be a problem. It was not possible to test back then though, since there was no active Yoodle. It should work in offline mode I think though. It probably also is account-specific.

**Comment by bhackel** [comment]
Yoodle is no longer active so I can't fix it, but it should be working now. Although Fake Premium is currently broken in latest build. I will wait for Yoodle to come back and then work on fixing it. I found this website that tracks past Yoodles: https://logos.fandom.com/wiki/YouTube/Yoodles#2024
