### ISSUE TITLE
[Bug] Crashes on open

### ISSUE THREAD

**Issue by yodaluca23** [arichornlover/uYouEnhanced#548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

iOS 16.4.1

### Device model

iPhone 14 Pro

### Sideload tool

Sideloadly

### Tweak version

uYouEnhanced Commit 853e5a1a1049397b7c3171285d96f34eb2a16aa3

### Describe the bug

Crashes as soon as I open the app.

### Steps to reproduce the issue

1. 
2. 
3. 

### Crash log (if the app crashes)

```shell
https://pastebin.com/AK9NiLVe
```

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by ANTONBORODA** [comment]
I have the same issue. The app crashes when opening any video. Disabling sponsorblock does not fix the issue. The crash report seems to be similar to one in the post.
https://pastebin.com/MxhTwjfB

**Comment by yodaluca23** [comment]
> I have the same issue. The app crashes when opening any video. Disabling sponsorblock does not fix the issue. The crash report seems to be similar to one in the post.
> 
> https://pastebin.com/MxhTwjfB

No, it's not just when opening a video, it's when opening the app at all...

**Comment by JellyPeixe** [comment]
Hey @ANTONBORODA , I had the same issue starting today and I think I found the solution by seeing your crash log. Test if this fix your issue and reach back to confirm if it helped: Go to uYou Tab>Red Cog(Config)>Video Player and disable "playback Speed Controls". Restart the App after that and see if video crashing stops.

**Comment by ANTONBORODA** [comment]
> Hey @ANTONBORODA , I had the same issue starting today and I think I found the solution by seeing your crash log. Test if this fix your issue and reach back to confirm if it helped: Go to uYou Tab>Red Cog(Config)>Video Player and disable "playback Speed Controls". Restart the App after that and see if video crashing stops.

Yes, the crashing stops with speed controls disabled. 
Thank for the workaround.

**Comment by ANTONBORODA** [comment]
It was working for a day yesterday, today it started crashing again.
It goes a bit further, the video starts to play for a second or two and then the app crashes when the stuff at the bottom (other videos, description, comments, etc.) loads in.

https://pastebin.com/rHu5r1K8

**Comment by JellyPeixe** [comment]
> It was working for a day yesterday, today it started crashing again.
> 
> It goes a bit further, the video starts to play for a second or two and then the app crashes when the stuff at the bottom (other videos, description, comments, etc.) loads in.
> 
> 
> 
> https://pastebin.com/rHu5r1K8
> 
> 
> 
> The issue seems to be with "return dislike" functionality. If I disable it - video plays normally.
> 
> 
> 
> Is g00gle actively trying to break tweaked apps?

Sadly, yes. Major news sources reported that google started a crackdown on modified clients and adblocking. Hopefully the Adblock community is very resilient and will survive yet again this new problem.

**Comment by misa198** [comment]
I have the same issue. I can't open the app.
