### ISSUE TITLE
[v19.14.2-3.0.3]%20Añada%20aquí%20su%20título...

### ISSUE THREAD

**Issue by Goss18** [arichornlover/uYouEnhanced#550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

17.5 beta 2

### Device model

13 pro max

### Sideload tool

Altstore

### Tweak version

19.14.2-3.0.3

### Describe the bug

No reproduce el video siguiente automáticamente 

### Steps to reproduce the issue

1. 
2. 
3. 

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by KingGamingYT** [comment]
¿Esto es con autoplay desactivado o habilitado? Se agradecerían más detalles.

**Comment by bhackel** [comment]
Enable uYou settings -> Video Player -> No suggested video at the video end. The setting is broken. It is backwards

**Comment by bhackel** [comment]
The name of the setting is wrong, and it does the opposite of what it says. So, if you enable No suggested Videos at the Video End, it will do the opposite, and allow suggested videos at the end. This will also allow autoplay to work
