### ISSUE TITLE
Hide Indicators Not working

### ISSUE THREAD

**Issue by yodaluca23** [arichornlover/uYouEnhanced#552]
Hide indicators is enabled, and I see numbers next to bell icon.

**Comment by KarmaBeast** [comment]
What are you referring to? Got screenshot?

**Comment by yodaluca23** [comment]
> What are you referring to? Got screenshot?

![image](https://github.com/arichornlover/uYouEnhanced/assets/67206487/ec32f766-bd04-42f9-910e-8097a5bdaadd)

**Comment by yodaluca23** [comment]
@arichornlover Can you fix this?

**Comment by yodaluca23** [comment]
Noticed this commit cf5c6e0, rebuilt, and it's still not working...

**Comment by yodaluca23** [comment]
> Noticed this commit [cf5c6e0](https://github.com/arichornlover/uYouEnhanced/commit/cf5c6e0ccd07421d0637f34550c12cd0408fc2b7), rebuilt, and it's still not working...

When I enable Flex, I am able to toggle the "@property BOOL hidden", for the "YTCountView" element, and that works, could you maybe implement that?

**Comment by yodaluca23** [comment]
That still didn't work 😭

**Comment by yodaluca23** [comment]
> Hey try building the uYouEnhanced ipa again, I think I fixed it.

Yep, that works, TYSM as always 😊
