### ISSUE TITLE
[Bug] Previews of videos and shorts in Russia are not loading

### ISSUE THREAD

**Issue by waterosem** [arichornlover/uYouEnhanced#554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

17.4.1

### Device model

iPhone 12

### Sideload tool

AltStore

### Tweak version

uYouEnhanced 19.14.2

### Describe the bug

The videos themselves are uploaded, but they are not uploaded from the preview, which makes it very inconvenient to use YouTube. There is no such problem in the original one downloaded from appstore
the previews are loading with the VPN app
### Steps to reproduce the issue

1. Live in Russia
2. Start uYouEnhanced
3. And watch the gray windows instead of previews

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by waterosem** [comment]
![IMG_1612](https://github.com/arichornlover/uYouEnhanced/assets/97552276/b3841805-e774-4b45-bcc4-38a68bf185bd)

**Comment by st3pash** [comment]
Isn't it caused by your ISP? I'm from Russia too, but thumbnails work as expected. As I remember, [this interpretation of YouTube](https://github.com/YTLitePlus/YTLitePlus) has a special tweak to help Russian users.
