### ISSUE TITLE
[Bug] YouPiP "Use PiP button" option causing app to crash

### ISSUE THREAD

**Issue by Kenry021** [arichornlover/uYouEnhanced#556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

17.4.1

### Device model

iPhone 13 Pro

### Sideload tool

AltStore

### Tweak version

v19.14.2-3.0.3

### Describe the bug

Enabling "Use PiP button" in YouPiP settings and using the pip button in the video control overlay will cause the app to crash.

https://github.com/arichornlover/uYouEnhanced/assets/101542293/b32e8506-59c1-4fc3-85b5-215bd61f05e4

### Steps to reproduce the issue

1. Enable "Use PiP button" in YouPiP settings
2. Go into any video and click the icon in video tab bar 
3. Crash

### Crash log (if the app crashes)

```shell
https://pastebin.com/gC9KGcqP
```

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by defrt** [comment]
Try to use tab bar pip button

**Comment by Kenry021** [comment]
> Try to use tab bar pip button

I tried it, and it works. Just not "Use PiP button"

**Comment by Kenry021** [comment]
Fixed: https://twitter.com/PoomSmart/status/1783110381462069456
