### ISSUE TITLE
crashing when starting playing any video

### ISSUE THREAD

**Issue by NotADinosaur** [arichornlover/uYouEnhanced#558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

ios 17.0

### Device model

iphone 12

### Sideload tool

sideloadly

### Tweak version

19.14.2-3.0.3

### Describe the bug

I updated it to fix the isponsorblock issue, and it worked for a few days before it stopped and now the app crashes when pressing on any video to start it. I don’t remember changing any settings before it stopped working, which is weird if that’s correct. Also it happens regardless of whether isponsorblock is on or off so it’s not still that.

### Steps to reproduce the issue

it’s pretty obvious…

### Crash log (if the app crashes)

```shell
I’m not sure where this is as there’s several and none are from today even though it’s crashed today?
```

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by defrt** [comment]
Disable playback speed controls from uyou settings.  Its in video player section

**Comment by NotADinosaur** [comment]
thanks, that seems to have fixed it

**Comment by eobi1976** [comment]
I literally just disabled that too and it’s now working again for me. Is this a temporary fix?

**Comment by FriedEngineer** [comment]
It looks like this issue will be resolved shortly. It was fixed in https://github.com/qnblackcat/uYouPlus/pull/1428 and those changes have been pulled into uYouEnhanced in https://github.com/arichornlover/uYouEnhanced/commit/52937e16cb9d6b3742ba21a719d527f7d69832c4.
