### ISSUE TITLE
[Bug] YouTube crashes when trying to play video

### ISSUE THREAD

**Issue by andre1808** [arichornlover/uYouEnhanced#578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

17.4.2

### Device model

iPhone 15 pro

### Sideload tool

SideStore

### Tweak version

19.14.2

### Describe the bug

When trying to open a video, YouTube just closes. 
Shorts are working fine. 
This issue has been present in the past already and came back yesterday.

disabling sponsorblock does not help this time. 

### Steps to reproduce the issue

1. start YouTube 
2. try to open any video

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by corbenc388** [comment]
Same issue for me, I’ve disable almost all the big uYouEnhanced settings with no luck

**Comment by corbenc388** [comment]
Found the fix, it was answered about a week ago in one of these threads 
https://github.com/arichornlover/uYouEnhanced/issues/558#issuecomment-2067936138
gotta disable speed controls

**Comment by andre1808** [comment]
> Found the fix, it was answered about a week ago in one of these threads [#558 (comment)](https://github.com/arichornlover/uYouEnhanced/issues/558#issuecomment-2067936138) gotta disable speed controls

Thank you, this really fixes it for me. Why did I not find that before?! :(
Thanks for the fast help and support to all replies.

**Comment by OmniiOMEGA** [comment]
> Found the fix, it was answered about a week ago in one of these threads 
> 
> https://github.com/arichornlover/uYouEnhanced/issues/558#issuecomment-2067936138
> 
> gotta disable speed controls 

Where is this?

**Comment by OmniiOMEGA** [comment]
> > Found the fix, it was answered about a week ago in one of these threads 
> > 
> > https://github.com/arichornlover/uYouEnhanced/issues/558#issuecomment-2067936138
> > 
> > gotta disable speed controls 
> 
> Where is this?

Found it, hopefully fix coming soon as it only started today which is odd

**Comment by DennyLiao607** [comment]
I disable youtube ads and playback speed control, then it works
But only disable playback speed control still crash the app

**Comment by DennyLiao607** [comment]
I also found out that disable speed control and isponsorblock these 2 can work properly

**Comment by noahnao** [comment]
I can't find the option to disable speed control, can someone please tell me where the setting is located?

**Comment by OmniiOMEGA** [comment]
> I can't find the option to disable speed control, can someone please tell me where the setting is located?

I had the same issue lol go to YouTube > You > Cog or Settings > General > uYou at Top > scroll a little then select video player under YouTube settings header > flick switch for Playback Speed Controls

**Comment by Xytriza** [comment]
same issue
i hate this bug bc shorts r bad
