### ISSUE TITLE
[Bug] Black Area When Scrolling Down Through Subscriptions

### ISSUE THREAD

**Issue by TheNightRider12** [arichornlover/uYouEnhanced#579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

iOS 17.4.1

### Device model

iPhone 13

### Sideload tool

Alt Store

### Tweak version

YouTube 19.16.3. v3.0.3

### Describe the bug

When I am scrolling through "Subscriptions" after scrolling through a few of them I am then greeted with a black section. When I continue scrolling, then I am greeted with the rest of my subscription's videos. The setting "AdBlock Workaround" is disabled. This happens even when that setting is enabled. 

### Steps to reproduce the issue

![IMG_4143](https://github.com/arichornlover/uYouEnhanced/assets/8153239/ec4a61fa-7d52-49f5-a8d2-d8ffd0246749)

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by 02tz** [comment]
> disable uYou adblocking, or if you have a build from less than 2 days ago, turn off Adblock Workaround in uYouEnhanced settings

it fixed the issue, but the only reason i use uyou is for adblock 😭😭

**Comment by bhackel** [comment]
Ah that is unfortunate, I was hoping that it was a part of the workaround code - if it’s in uYou, then we can’t fix it. Anyway, the setting is in uYou Tab -> Settings -> Other Settings -> Remove Ads

**Comment by bhackel** [comment]
Ah if you are seeing blank spaces on the subscription page, that might be from using Remove Shorts Cells in uYou Settings
