### ISSUE TITLE
Blank Screen Glitch

### ISSUE THREAD

**Issue by JACKKY04** [arichornlover/uYouEnhanced#583]
https://github.com/arichornlover/uYouEnhanced/assets/79938424/e9a285f6-64ca-45ea-be41-165ecc600459

**Comment by defrt** [comment]
Same here. Work around is turning off ads block from uyou settings. But it's defeating the purpose

**Comment by sachit-menon** [comment]
Started happening for me today as well. Is there any idea why, or other workaround?

**Comment by borismul** [comment]
Same here. Anyone knows a fix?

**Comment by JACKKY04** [comment]
> Workaround without disabling ads here: https://github.com/arichornlover/uYouEnhanced/issues/529#issuecomment-2065625732

Can confirm this works for me.

**Comment by sachit-menon** [comment]
works for me too, thanks @borismul !

**Comment by ngntriminh** [comment]
New workaround without disabling ads: `Profile` > `Settings` > `uYouEnhanced` > disable `Hide Community Posts`. It works for me.
