### ISSUE TITLE
[Request] Option to disable the shadow that when you see back to the app

### ISSUE THREAD

**Issue by rommel4r** [arichornlover/uYouEnhanced#584]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

When you use PiP and get back to Youtube, there is a shadow on video and makes hard to watch video for a couple of seconds everytime. I believe it can be disabled easily. I am adding a picture below.

![IMG_0506](https://github.com/arichornlover/uYouEnhanced/assets/145980537/181c0c2d-5108-4594-921e-3bf09a6a0414)

**Comment by bhackel** [comment]
Is this different than the pause overlay? You can try disable that in the settings to see

**Comment by rommel4r** [comment]
> Is this different than the pause overlay? You can try disable that in the settings to see

I only found pause buttons overlay. Is there an option for all pause screen? If so, where is it?
