### ISSUE TITLE
[v19.16.3-3.0.3]%20Blank%20home%20page

### ISSUE THREAD

**Issue by FLSM777** [arichornlover/uYouEnhanced#586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

14.4.1

### Device model

14 pro max

### Sideload tool

Altstore

### Tweak version

uYouEnhanced 19.6.3-3.0.3 

### Describe the bug

Hey, after launching Youtube the first thing that i see is blank home page, after some scrolling down some things load but when i return to the top end its again blank

### Steps to reproduce the issue

1. 
2. 
3. 
![IMG_7613](https://github.com/arichornlover/uYouEnhanced/assets/72662389/924d8509-272a-47a4-ab23-ae29b87e926b)
![IMG_7614](https://github.com/arichornlover/uYouEnhanced/assets/72662389/f026b5b2-d2a9-46d3-81cb-0884ea6ded78)

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by Mukul1127** [comment]
Same

**Comment by defrt** [comment]
It's become huge pain in the ass

**Comment by ngntriminh** [comment]
uYou > YouTube Settings > Other Settings > Turn off Remove YouTube Ads. This is the temporary workaround, you will see ads on the home page but I think we have to accept it, at least I don't see ads in videos for now.

**Comment by FLSM777** [comment]
> uYou > YouTube Settings > Other Settings > Turn off Remove YouTube Ads.
thanks that helped
