### ISSUE TITLE
Cant turn off "Fix LowContrastmode"

### ISSUE THREAD

**Issue by Cagecellag** [arichornlover/uYouEnhanced#587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

17.3.1

### Device model

iPhone SE 2020

### Sideload tool

FlekSt0re

### Tweak version

uYouEnhanced 19.16.3 - 3.0.3

### Describe the bug

It doesn't matter how many times i turn the setting off and restart the app it just stays on, i repeated this like 10 times

### Steps to reproduce the issue

1. Turn off "Fix LowContrastMode"
2. Restart app

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

Literally cant turn it off lol

**Comment by Cagecellag** [comment]
> I was able to turn it off?

interesting, idk how but how??

**Comment by bhackel** [comment]
@Cagecellag do you have YTNoModernUI enabled? It will force-enable other settings

**Comment by Cagecellag** [comment]
> @Cagecellag do you have YTNoModernUI enabled? It will force-enable other settings

ups yea, i do indeed have it on. I was able to turn ot off now lol, thanks

**Comment by bhackel** [comment]
Ah good to know. I will add a warning to make it clearer
