### ISSUE TITLE
[Bug] BigYTMiniPlayer always enabled regardless of setting

### ISSUE THREAD

**Issue by Hazza42** [arichornlover/uYouEnhanced#600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

17.4.1

### Device model

iPhone 15 Pro Max

### Sideload tool

AltStore

### Tweak version

uYouEnhanced 19.16.3

### Describe the bug

I always get the large YouTube mini player even though I’ve toggled it off in settings. The toggle seems to have no effect now.

### Steps to reproduce the issue

1. Play video and swipe down to trigger mini player
2. Mini player is the large one that only occupies a corner and not the whole bottom bar
3. Toggle BigTYMiniPlayer off in settings
4. Restart app
5. Repeat step 1, mini player is still large

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by Hazza42** [comment]
Literally found a solution to this the moment I posted it. Simply went into A/B settings and hit ‘reset and kill’. Mini player no respects the toggle now

**Comment by bhackel** [comment]
Ah makes sense - can you close this issue then?
