### ISSUE TITLE
[Bug] The home page is partially blank

### ISSUE THREAD

**Issue by misa198** [arichornlover/uYouEnhanced#604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the Wiki?

- [X] Yes, I have read the Wiki

### iOS/iPadOS version

iOS 17.0.2

### Device model

iPhone 11

### Sideload method

Sideloadly

### Tweak version

19.16.3 - 3.0.3

### Do you have Youtube Premium?

- [ ] Yes, I have Youtube Premium

### Describe the bug

Some videos on the homepage are missing, when I scroll down a bit they appear, but sometimes when I scroll back up and down they disappear. I have disabled “adblock workaround”.

[Watch the video](https://imgur.com/a/PF0A2Nd)

![IMG_2218](https://github.com/arichornlover/uYouEnhanced/assets/51451216/5498a557-49b4-476d-ada1-8caa00504251)

### Steps to reproduce the issue

1. 
2. 
3. 

### Are you using the newest version of uYouEnhanced?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by PoloNX** [comment]
Did you find a fix ?

**Comment by misa198** [comment]
> Did you find a fix ?

No, i didn't

**Comment by bhackel** [comment]
Current fix is to disable uYou ad blocking in uYou Other Settings

**Comment by misa198** [comment]
@bhackel Confirmed. Thank you!
