### ISSUE TITLE
 Unable to cast, Local area network access required, unable to cast

### ISSUE THREAD

**Issue by YabberWalkie** [arichornlover/uYouEnhanced#606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the Wiki?

- [X] Yes, I have read the Wiki

### iOS/iPadOS version

iOS 17.4.1

### Device model

iPhone 12

### Sideload method

Signulous 

### Tweak version

19.16.3-3.0.3

### Do you have Youtube Premium?

- [ ] Yes, I have Youtube Premium

### Describe the bug

I’m suddenly unable to cast any videos using the cast button. I keep getting the message that local area network access is required and then opens the settings panel for YouTube where it is already enabled.

I’ve uninstalled and restarted my iPhone and the first time I get the message to enable access, which I granted but then clicking the cast button does nothing and restarting the app then just complains about the local network access required.

This doesn’t appear to be uYouEnhanced specific as it also happens to uyou but I’m not sure what changed for the casting to not work anymore.

### Steps to reproduce the issue

Open a video and click the cast button

### Crash log (if the app crashes)

```shell
Na
```

### Are you using the newest version of uYouEnhanced?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

N.a.

**Comment by mohkg1017** [comment]
same issue

**Comment by mohkg1017** [comment]
casting is broken
