### ISSUE TITLE
[Bug] Process completed with exit code 2

### ISSUE THREAD

**Issue by ryanlimdx** [arichornlover/uYouEnhanced#608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the Wiki?

- [X] Yes, I have read the Wiki

### iOS/iPadOS version

IPadOS 17.4.1

### Device model

iPad Pro (3rd Generation)

### Sideload method

SideStore

### Tweak version

uYouEnhanced - (v19.16.3-3.0.3)

### Do you have Youtube Premium?

- [ ] Yes, I have Youtube Premium

### Describe the bug

I have used a public dropbox link as mentioned in the build guide, and sync the fork to the latest version. However, when building, it says process completed with exit code 2.

### Steps to reproduce the issue

1. Github Issue
![image](https://github.com/arichornlover/uYouEnhanced/assets/91833948/c3b2730d-b36f-48b5-8bcf-fd4402903d76)

2.  Dropbox Public URL
![image](https://github.com/arichornlover/uYouEnhanced/assets/91833948/533ef6a4-4557-46a2-bc46-564c5cb6a25e)
 

### Are you using the newest version of uYouEnhanced?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by bhackel** [comment]
Google drive links do not work for using IPAs. We recommend using dropbox or litterbox

**Comment by bhackel** [comment]
Actually you are using dropbox which should work. I remember something about someone saying that you need to remove the stuff after the ? in the address bar or something. Or just use litterbox: https://litterbox.catbox.moe/

**Comment by ryanlimdx** [comment]
@bhackel May I know how to use Litterbox to generate the required direct URL? I am unable to get a link from litterbox to include. As for dropbox, I have removed the portion after the '?' and I am getting exit code 9 instead.. Thanks for the help so far!

**Comment by ryanlimdx** [comment]
![image](https://github.com/arichornlover/uYouEnhanced/assets/91833948/c7f25c4f-7e1f-4a72-80d9-62e4486cbc83)
This is the detailed error message
