### ISSUE TITLE
Logo for uYouEnhanced GitHub?

### ISSUE THREAD

**Issue by KarmaBeast** [arichornlover/uYouEnhanced#613]
Is there a logo of uYouEnhanced that I can use?

I'm not talking about this ugly uYou logo below:![image](https://github.com/arichornlover/uYouEnhanced/assets/73917917/a8f269df-cfed-478b-b160-387a66efcc74)

Just a logo specifically for uYouEnhanced? Want to use it for the telegram group. The GitHub repo is some anime picture 🫤

**Comment by yodaluca23** [comment]
> Also the white background etc. I'm not sure now 😐

It's transparent background on my end
