### ISSUE TITLE
[Questions] Best way to sideload apps without resigning the app every few weeks.

### ISSUE THREAD

**Issue by iiasceri** [arichornlover/uYouEnhanced#642]
### Best way to sideload apps without resigning the app every few weeks.
* Europe
* Latest iPad
* uYouEnhanced
* Kinda sucks paying 100$ or signing every 14 days the ipa ...

**Comment by iiasceri** [comment]
Found the answer:
https://apptesters.org/purchase-certificate/
you buy 25$ certificate for 1 device lifetime if you want to ofc

**Comment by bhackel** [comment]
Maplesign is $7.5 for 1 device, I use that. Also, this technique is free, you should try it https://www.reddit.com/u/PuReEnVyUs/s/SmAy04g1GR
