### ISSUE TITLE
[Bug] Videos in Playlist Disappear

### ISSUE THREAD

**Issue by Invisible40** [arichornlover/uYouEnhanced#658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the Wiki?

- [X] Yes, I have read the Wiki

### iOS/iPadOS version

iOS 16.0.1

### Device model

iPhone 13

### Sideload method

TrollStore

### Tweak version

uYouEnhanced 19.20.2-3.0.3

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Describe the bug

Videos in playlists sometimes disappear. I’ve attached a video of what happens:

https://github.com/arichornlover/uYouEnhanced/assets/8390311/0d4423b9-f6ab-411a-91ad-bb9592888b35

I did not get this issue with past versions of uYouEnhanced

below are my settings: 

slideToSeek_enabled: 0
enableSaveToButton_enabled: 1
hideYTMusicButton_enabled: 1
hideAutoplaySwitch_enabled: 1
hidePaidPromotionCard_enabled: 1
hideChannelWatermark_enabled: 1
redProgressBar_enabled: 0
hideHoverCards_enabled: 0
noSuggestedVideo_enabled: 1
disableAmbientMode_enabled: 0
hideBuySuperThanks_enabled: 1
hideRemixButton_enabled: 1
hideThanksButton_enabled: 1
hideDownloadButton_enabled: 1
hideClipButton_enabled: 1
hidePremiumPromos_enabled: 1
fixLowContrastMode_enabled: 0
disableModernButtons_enabled: 0
disableRoundedHints_enabled: 0
disableModernFlags_enabled: 0
enableVersionSpoofer_enabled: 0
uYouAdBlockingWorkaroundLite_enabled: 1
uYouAdBlockingWorkaround_enabled: 1
uYouAdBlockingWorkaround_enabled: 1
hideSponsorBlockButton_enabled: 1
hidePlayNextInQueue_enabled: 1
reExplore_enabled: 1
fixCasting_enabled: 1
relatedVideosAtTheEndOfYTVideos: 1
disableAgeRestriction: 0
removeYouTubeAds: 1
noSuggestedVideoAtEnd: 1
showedWelcomeVC: 1
shortsProgressBar: 1
removeShortsCell: 1

### Steps to reproduce the issue

1.  Open playlist
2. Videos are sometimes gone

### Are you using the newest version of uYouEnhanced?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by bhackel** [comment]
It's probably some adblocking issue again. If you want to, you can try messing with the adblock settings to see if anything fixes it

**Comment by Invisible40** [comment]
Tried this and did not work, same as before. To reiterate, the settings are now:

slideToSeek_enabled: 0
enableSaveToButton_enabled: 1
hideYTMusicButton_enabled: 1
hideAutoplaySwitch_enabled: 1
hidePaidPromotionCard_enabled: 1
hideChannelWatermark_enabled: 1
redProgressBar_enabled: 0
hideHoverCards_enabled: 0
noSuggestedVideo_enabled: 0
disableAmbientMode_enabled: 0
hideBuySuperThanks_enabled: 1
hideRemixButton_enabled: 1
hideThanksButton_enabled: 1
hideDownloadButton_enabled: 1
hideClipButton_enabled: 1
hidePremiumPromos_enabled: 1
fixLowContrastMode_enabled: 0
disableModernButtons_enabled: 0
disableRoundedHints_enabled: 0
disableModernFlags_enabled: 0
enableVersionSpoofer_enabled: 0
uYouAdBlockingWorkaroundLite_enabled: 1
uYouAdBlockingWorkaround_enabled: 0
uYouAdBlockingWorkaround_enabled: 0
hideSponsorBlockButton_enabled: 1
hidePlayNextInQueue_enabled: 1
reExplore_enabled: 1
fixCasting_enabled: 1
relatedVideosAtTheEndOfYTVideos: 1
disableAgeRestriction: 0
removeYouTubeAds: 0
noSuggestedVideoAtEnd: 1
showedWelcomeVC: 1
shortsProgressBar: 1
removeShortsCell: 1

**Comment by Invisible40** [comment]
If it helps, the version I used when I did not get this issue was 19.04.3-3.0.1

**Comment by Invisible40** [comment]
Problem is solved; [this fixed it](https://github.com/arichornlover/uYouEnhanced/issues/708#issuecomment-2159650258).
