### ISSUE TITLE
[Bug] Replace this with your title

### ISSUE THREAD

**Issue by Austinnnns** [arichornlover/uYouEnhanced#671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the Wiki?

- [X] Yes, I have read the Wiki

### iOS/iPadOS version

17.4.1

### Device model

Iphone 15

### Sideload method

Esign

### Tweak version

19.21.2 3.0.4

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Describe the bug

Building stops on preparing youtube ipa. Using litterbox to upload decrypted ipa. Previous update worked fine so idk.

### Steps to reproduce the issue

1. 
2. 
3. 

### Are you using the newest version of uYouEnhanced?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by bhackel** [comment]
It looks like it worked for you after a long time, not sure why the download took forever
