### ISSUE TITLE
[Bug] Error Compiling After Latest Commits

### ISSUE THREAD

**Issue by TheNightRider12** [arichornlover/uYouEnhanced#686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the Wiki?

- [X] Yes, I have read the Wiki

### iOS/iPadOS version

iOS 17.5.1

### Device model

iPhone 13

### Sideload method

Signulous

### Tweak version

3.0.4

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Describe the bug

When building the latest commits against the latest IPA, there is an error when building. I believe the errors are caused by the latest submodules update. Here is a screenshot of the error output under Actions
![firefox_pyDONAk64j](https://github.com/arichornlover/uYouEnhanced/assets/8153239/eeb31473-087f-4112-96e9-b487fa8cc6dc)

### Steps to reproduce the issue

1. Sync the fork against the upstream repository
2.  Attempt to build the app using Github actions
3. 

### Are you using the newest version of uYouEnhanced?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by mohkg1017** [comment]
same issue
