### ISSUE TITLE
Pip

### ISSUE THREAD

**Issue by HarutKing46** [arichornlover/uYouEnhanced#704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Is there a way to entirely turn off pip every time I exit the app the audio of the video still plays.

**Comment by HarutKing46** [comment]
Didn’t work

**Comment by bhackel** [comment]
Youtube Settings -> YouPiP -> Turn off Enabled, see if that does anything

**Comment by HarutKing46** [comment]
Nope nothing

**Comment by HarutKing46** [comment]
.
