### ISSUE TITLE
[v19.21.2-3.0.4] Custom app icon error

### ISSUE THREAD

**Issue by SKempiak** [arichornlover/uYouEnhanced#710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the Wiki?

- [X] Yes, I have read the Wiki

### iOS/iPadOS version

iOS 17.5.1

### Device model

iPhone 15 pro max

### Sideload method

AltStore

### Tweak version

youEnhanced - v19.21.2-3.0.4

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Describe the bug

I tried this on my iPad as well, pro gen 5 I believe. Both are unable to set the new icon.

![IMG_0082](https://github.com/arichornlover/uYouEnhanced/assets/28799140/f0cddc0a-35a0-4cfd-bced-0bb0b68d5582)

### Steps to reproduce the issue

1. Go to you > settings > uYouEnhanced
2. Change App Icon
3. Try an icon for a generic error

### Are you using the newest version of uYouEnhanced?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Select the configuration used for building uYouEnhanced ipa.

- [ ] buildapp.yml
- [ ] build.sh

**Comment by SKempiak** [comment]
Very sorry for the ignorant post.

**Comment by samuelawachie** [comment]
> Very sorry for the ignorant post.
>
So did you manage to change the icon? Or is it not applicable for this application? It's something I would like to do and I always get stymied by that same error that dogged you.
