### ISSUE TITLE
[Questions] where to find v19.21.3-3.0.4? I see people talking about it but it’s not in release tab

### ISSUE THREAD

**Issue by jaycomma** [arichornlover/uYouEnhanced#712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Where is v19.21.3-3.0.4? It is not in releases tab?

### Additional context

People say the crash upon opening video bug is fixed in v19.21.3 but i can’t find it in releases. Am I crazy?

**Comment by jimmysofat6864** [comment]
You have to follow the build instructions to generate your own iPA as it said in the releases tab. 

https://github.com/arichornlover/uYouEnhanced/releases/tag/v19.21.2-3.0.4

**Comment by jaycomma** [comment]
> You have to follow the build instructions to generate your own iPA as it said in the releases tab.
> 
> https://github.com/arichornlover/uYouEnhanced/releases/tag/v19.21.2-3.0.4

I am having no trouble building the app, I know how to do that. But am i cool just compiling the IPA with the newer version of YouTube (19.21.3) instead of using 19.21.2?

**Comment by Driek123** [comment]
Yes you just need to find the corresponding ipa,  
The actual ipa cannot be shared here due to the DMCA this project & other modified yt forks got a while back. 

Personally for me other versions of the app are working rather than 19.21.3. Just compile and test if it works for you.

**Comment by jimmysofat6864** [comment]
I honestly don’t check I just compile with the latest versions and that had
always worked for me just try with the latest or same version and see what
happens.

**Comment by Invisible40** [comment]
For me, YouTube 19.24.2 does not work with the most recent release of uYouEnhanced
