### ISSUE TITLE
[Bug] app Crash when i play video (YT v. 19.24.3)

### ISSUE THREAD

**Issue by Jazooxd** [arichornlover/uYouEnhanced#738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the Wiki?

- [X] Yes, I have read the Wiki

### iOS/iPadOS version

iOS 16.1

### Device model

iPhone 10

### Sideload method

TrollStore

### Tweak version

uYouEnhanced - v19.24.3-3.0.4

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Describe the bug

when i play video app crashed (same situasion with sort but it is fix...)

video:
https://github.com/arichornlover/uYouEnhanced/assets/166530795/fc67ebac-4577-4e7a-b7cd-1a4b3acd12ac

### Steps to reproduce the issue

1. open YouTube 
2. Play any video
3. App Crash

video:
https://github.com/arichornlover/uYouEnhanced/assets/166530795/6c05d45c-914f-4c24-bd26-e8be9be52011

### Crash log (if the app crashes)

```shell
my Crash log:

https://gofile.io/d/8EPK0a
```

### Are you using the newest version of uYouEnhanced?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Select the configuration used for building the uYouEnhanced ipa. (Optional)

- [X] buildapp.yml (GitHub Actions — build method as suggested by [Wiki - Building](https://github.com/arichornlover/uYouEnhanced/wiki/Building))
- [ ] build.sh (Shell script)

**Comment by lts20050703** [comment]
I'm using `v19.24.2-3.0.4` and it crash when I try to play any video

**Comment by Mukul1127** [comment]
Same

**Comment by Mukul1127** [comment]
This may fix it: https://github.com/PoomSmart/Return-YouTube-Dislikes/commit/7374b7c4e0225ba5dd9bfc13634bc3cbb87c9fc4

**Comment by Jazooxd** [comment]
> I didn’t even realize RYD broke, I’ll update it.

okay thank you

**Comment by Jazooxd** [comment]
its fix Thank you
