### ISSUE TITLE
[Bug] adblock broke home page

### ISSUE THREAD

**Issue by ryuku1208** [arichornlover/uYouEnhanced#746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the Wiki?

- [X] Yes, I have read the Wiki

### iOS/iPadOS version

ios 17.5

### Device model

Iphone 15 Pro Max

### Sideload method

dev accounts sideload

### Tweak version

uYouEnhanced 19.24.3-3.0.4

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Describe the bug

when I’m enable adblock work around. the home page would be just black and show no video. turn off adblock and using the adblock lite, video show back as normal but also the ads is showing too on the home page

### Steps to reproduce the issue

1. turn off adblock on uYou, Adblock workaround (Lite), Adblock workaround on uYouEnhanced.
2. turn on each adblock one by one and restart each time.
3. adblock on uYou and Adblock workaround on uYouEnhanced will make the Home page go blank
4. Adblock workaround (Lite) wont but the ads will show

### Are you using the newest version of uYouEnhanced?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Select the configuration used for building the uYouEnhanced ipa. (Optional)

- [X] buildapp.yml (GitHub Actions — build method as suggested by [Wiki - Building](https://github.com/arichornlover/uYouEnhanced/wiki/Building))
- [ ] build.sh (Shell script)

**Comment by ryuku1208** [comment]
> I recommend building with the latest changes from uYouEnhanced, I updated the option earlier today.

i sync every time before i build the new ipa, its up to day

**Comment by ryuku1208** [comment]
> > > I recommend building with the latest changes from uYouEnhanced, I updated the option earlier today.
> > 
> > 
> > i sync every time before i build the new ipa, its up to day
> 
> Hmm.
> 
> heres a workaround: swipe up when the home tab is blank, it should make everything re-appear.

it is but it not working all the time, and the video will disappear when you go up 
it is more annoying than the ads itself so im just im just with ads right now, report this as bug hopefully the dev update uYou to fix it soon

**Comment by Yunogamer** [comment]
ytliteplus on 19.22.3 doesnt have this issue so.. someone fixed something..

**Comment by ryuku1208** [comment]
new update fix it, thank dev
