### ISSUE TITLE
[Bug] Unable to signin to google account

### ISSUE THREAD

**Issue by ILNSuryaChandra** [arichornlover/uYouEnhanced#755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the Wiki?

- [X] Yes, I have read the Wiki

### iOS/iPadOS version

iOS 18

### Device model

iPhone 14 Plus

### Sideload method

AltStore

### Tweak version

uYouEnhanced 19.38.2 3.0.4

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Describe the bug

![telegram-cloud-photo-size-5-6325515207077641197-y](https://github.com/user-attachments/assets/e567f83e-60e0-4cf2-9239-ac29965e545a)
Unable to sign in to Google account. I have tried using old modified IPAs too which were working. it looks like it's from Google's end.

### Steps to reproduce the issue

1. Sideload uYouEnhanced IPA using Altstore
2. Open the app and click on sign in
3. try signing in.

### Are you using the newest version of uYouEnhanced?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Select the configuration used for building the uYouEnhanced ipa. (Optional)

- [X] buildapp.yml (GitHub Actions — build method as suggested by [Wiki - Building](https://github.com/arichornlover/uYouEnhanced/wiki/Building))
- [ ] build.sh (Shell script)

**Comment by jianmingyong** [comment]
Try enabling YT Sign in patch for those who use free developer accounts. (You may need to enable then restart for it to take effect)

After logging in, turn that thing off so you can have the icons back.

![IMG_9402](https://github.com/user-attachments/assets/8c9c6580-d2ba-4854-a956-446ca5d4b6c2)

**Comment by ILNSuryaChandra** [comment]
that worked! thanks. I guess I should have put some more effort.

**Comment by shiroizdabezt** [comment]
> Try enabling YT Sign in patch for those who use free developer accounts. (You may need to enable then restart for it to take effect)
> 
> After logging in, turn that thing off so you can have the icons back.
> 
> ![IMG_9402](https://private-user-images.githubusercontent.com/7069939/371854906-8c9c6580-d2ba-4854-a956-446ca5d4b6c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MjI2MTMsIm5iZiI6MTcyNzkyMjMxMywicGF0aCI6Ii83MDY5OTM5LzM3MTg1NDkwNi04YzljNjU4MC1kMmJhLTQ4NTQtYTk1Ni00NDZjYTVkNGI2YzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMDIyNTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWViMzg0YjJlMmY0NGE5ZTJhNGQ5MzhkNWRjZTJkMzFkOTBhNWFmNTNjMDVhNjBkYzljMTc4NGViODQzZDI2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.RAtulP38EBxorjFTzjYjOV_Bx0obIC0MzLrXasnFNKw)

Where can i find that? I’m using uyou enhanced 3.0.4 downloaded in website uyou plus enhanced

**Comment by jianmingyong** [comment]
> > Try enabling YT Sign in patch for those who use free developer accounts. (You may need to enable then restart for it to take effect)
> > After logging in, turn that thing off so you can have the icons back.
> > ![IMG_9402](https://private-user-images.githubusercontent.com/7069939/371854906-8c9c6580-d2ba-4854-a956-446ca5d4b6c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MjI2MTMsIm5iZiI6MTcyNzkyMjMxMywicGF0aCI6Ii83MDY5OTM5LzM3MTg1NDkwNi04YzljNjU4MC1kMmJhLTQ4NTQtYTk1Ni00NDZjYTVkNGI2YzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMDIyNTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWViMzg0YjJlMmY0NGE5ZTJhNGQ5MzhkNWRjZTJkMzFkOTBhNWFmNTNjMDVhNjBkYzljMTc4NGViODQzZDI2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.RAtulP38EBxorjFTzjYjOV_Bx0obIC0MzLrXasnFNKw)
> 
> Where can i find that? I’m using uyou enhanced 3.0.4 downloaded in website uyou plus enhanced

It is all the way down in the uYouEnhanced settings section. You will need to scroll up a bit when you are at the bottom of the setting.

**Comment by WeAreLegion999** [comment]
nice! thanks!

**Comment by Long18** [comment]
`YouTube Sign-in Patch` is gone!

![image](https://github.com/user-attachments/assets/df4cc18b-3762-4c1c-8ef1-6177570b7196)

**Comment by 1davi** [comment]
> > Try enabling YT Sign in patch for those who use free developer accounts. (You may need to enable then restart for it to take effect)
> > After logging in, turn that thing off so you can have the icons back.
> > ![IMG_9402](https://private-user-images.githubusercontent.com/7069939/371854906-8c9c6580-d2ba-4854-a956-446ca5d4b6c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNjQ2NzEsIm5iZiI6MTczMTE2NDM3MSwicGF0aCI6Ii83MDY5OTM5LzM3MTg1NDkwNi04YzljNjU4MC1kMmJhLTQ4NTQtYTk1Ni00NDZjYTVkNGI2YzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDlUMTQ1OTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDBmZjMyNjFiZDQ0OWQ0ODg3MzNiZWMyNGM4MzYwOGQ1ZDQ1MWY0MGU4NDcwYzczNDViOGEyZTVjYWE1OGUxOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.cknMWc_PQ_Sx0bNzTXNqywBpUNoIqrKPn63RH3wwwkA)
> 
> `YouTube Sign-in Patch` is gone!
> 
> ![image](https://private-user-images.githubusercontent.com/28853225/384618284-df4cc18b-3762-4c1c-8ef1-6177570b7196.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNDMwMzMsIm5iZiI6MTczNDM0MjczMywicGF0aCI6Ii8yODg1MzIyNS8zODQ2MTgyODQtZGY0Y2MxOGItMzc2Mi00YzFjLThlZjEtNjE3NzU3MGI3MTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA5NTIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlMzUxNWI2ZmE2ODdkOGI1YzBmOGJiNDM1OTUyNTkxMTYyZGQxMzI5MzI0YjRkODkwMjExYjY2NzZmOWE5NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JwqMycqndQqsC5JV21oTqz2yheKWaYYfsPTbVA9ElhA)

Same problem here
