### ISSUE TITLE
[Bug] Requries Additional Privacy and Entitlement Permissions, Continuing gives "storeApp is not valid"

### ISSUE THREAD

**Issue by JesterGithub0** [arichornlover/uYouEnhanced#760]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the Wiki?

- [X] Yes, I have read the Wiki

### iOS/iPadOS version

iOS 17.6.1

### Device model

iPhone 14

### Sideload method

AltStore Source (https://therealfoxster.github.io/altsource-viewer/view/?source=https://raw.githubusercontent.com/arichornlover/arichornlover.github.io/main/apps.json)

### Tweak version

19.33.2

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Describe the bug

Pop-up when trying to install uYouEnhanced via the AltStore source. See attached images. Older resolved issue has no fix, it just started working suddenly for them. Continuing past the warnings give the error "storeApp is not valid"
![IMG_0898](https://github.com/user-attachments/assets/21da6e9a-49a9-4b67-8243-3e9e81be0c14)
 ![IMG_0896](https://github.com/user-attachments/assets/ccaad340-9edb-448b-90f0-0cd6dd803beb)

### Steps to reproduce the issue

1. Add uYouEnhanced source on AltStore
2. Try to download app

### Are you using the newest version of uYouEnhanced?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by JesterGithub0** [comment]
> Hey @JesterGithub0 I have updated the source. Let me know if the popup is gone. 😅

Hey, thanks for doing this. Looks like the Entitlement permission is gone from the popup, but the User Tracking is still missing, but honestly I think that one is completely unnecessary. It installed with no issues once I hit "Install anyway."
Thanks again for fixing this so quick.

**Comment by JesterGithub0** [comment]
> > > Hey @JesterGithub0 I have updated the source. Let me know if the popup is gone. 😅
> > 
> > 
> > Hey, thanks for doing this. Looks like the Entitlement permission is gone from the popup, but the User Tracking is still missing. Honestly, I think that one is completely unnecessary. It installed with no issues once I hit "Install anyway." Thanks again for fixing this so quick.
> > Edit: Oops didn't mean to close the issue. Reopened in case you feel the need to fix the other permission.
> 
> I think when I was fixing it I probably accidentally called it **NSUserTrackingUsage-Description** because of the screenshot, I renamed it to **NSUserTrackingUsage-Description** in the AltSource now.
> 
> and soon I’m pushing out a uYouEnhanced 19.40.4 update.

Wait that's the same thing twice. Either way, thanks for the help again. App works fine even without it, doesn't seem like it's a big issue either.

**Comment by Dievale** [comment]
Hi, I just got the exact same message trying to install from alt store source (NSUserTrackingUsage-Description)

**Comment by JesterGithub0** [comment]
> Hi, I just got the exact same message trying to install from alt store source Privacy Permission: (NSUserTrackingUsage-Description)

You can continue with install, it worked fine for me.
