### ISSUE TITLE
[Questions] Internet Archive is down

### ISSUE THREAD

**Issue by Kleo08s** [arichornlover/uYouEnhanced#765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Internet Archive is down so i can’t install the program using AltStore. is there a way to install it for now? i just need the ipa file

**Comment by ivanivanusic** [comment]
Same for me

**Comment by yodaluca23** [comment]
Yea they've been getting DDOSed and hacking and stuff... Really sad, I don't know who would want to hurt IA...
https://www.bleepingcomputer.com/news/security/internet-archive-hacked-data-breach-impacts-31-million-users/

**Comment by aaronliu0130** [comment]
There are build-with-github instructions in the README

**Comment by gocciolafr** [comment]
> There are build-with-github instructions in the README

I don’t have a Mac I need the ipa file
