### ISSUE TITLE
Is it possible to save config when upgrading?

### ISSUE THREAD

**Issue by WoodpeckerBaby** [arichornlover/uYouEnhanced#77]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

Maybe have a way to export settings or save it to Google drive.

**Comment by Felting** [comment]
How are you signing it?

**Comment by Hex67** [comment]
> ### Have you read the FAQ?
> * [x]  Yes, I did read the FAQ
> 
> ### Is there an existing issue/question for this?
> * [x]  I have searched the existing issues
> 
> ### Do you think this is a bug?
> ❌ No, I don't think this is a bug. I will explain below
> 
> ### My question
> Maybe have a way to export settings or save it to Google drive.
> 
> ### Additional context
> _No response_

Yes, there is if your device is MacDirtyCow(MDC) bug supported then you can actually use filza and save the whole youtube data folder then restore it on the latest version, there’s one more way and this requires MDC too you can backup just your settings using Esign.
MacDirtyCow:
https://onejailbreak.com/blog/macdirtycow-tools/
Esign:
https://esign.yyyue.xyz/
FilzaEscaped16:
https://ipa.cypwn.xyz/serve/get.php?md5=6674dec1e1989cd7dad95839f321bfdd

You can ask me for a tutorial anytime you want :)
