### ISSUE TITLE
You can’t sign in to this app because Google can’t confirm that it’s safe.

### ISSUE THREAD

**Issue by Caitlynmcc234** [arichornlover/uYouEnhanced#775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the Wiki?

- [X] Yes, I have read the Wiki

### iOS/iPadOS version

iOS 18.1 beta 4

### Device model

iPhone 11

### Sideload method

Sidestore

### Tweak version

uYouEnhanced v19.41.3-3.0.4

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Describe the bug

I get this prompt when I try to sign in:
You can’t sign in to this app because Google can’t confirm that it’s safe.
![IMG_0003](https://github.com/user-attachments/assets/2e191755-e486-4de8-9c8c-3c29cb34bc45)
I think it’s the newest. I compiled it 5 days ago

### Steps to reproduce the issue

1. Install uyouenhanced ipa
2. Open it and try to sign in

### Are you using the newest version of uYouEnhanced?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Select the configuration used for building or obtaining the uYouEnhanced ipa. (Optional)

buildapp.yml (GitHub Actions — build method as suggested by [Wiki - Building](https://github.com/arichornlover/uYouEnhanced/wiki/Building))

**Comment by Long18** [comment]
> Go to YouTube Settings. ⚙️ Then, go to settings that are called **uYouEnhanced** once you are there search for **YouTube Sign-In Patch** and enabled it and now restart the app. Once you are signed into YouTube then just disable the option afterwards to fix the invisible icons bug.

`YouTube Sign-in Patch` is gone!

![image](https://github.com/user-attachments/assets/df4cc18b-3762-4c1c-8ef1-6177570b7196)
