### ISSUE TITLE
Ads are showing in the shorts feed 

### ISSUE THREAD

**Issue by Kryptikdream** [arichornlover/uYouEnhanced#787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the Wiki?

- [X] Yes, I have read the Wiki

### iOS/iPadOS version

iOS 18.1

### Device model

iPhone XR 

### Sideload method

Signulous

### Tweak version

uYouenhanced 19.44.4

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Describe the bug

Where a short is supposed to be from a channel, it shows an ad instead. It shows the channel name and title of the short but it’s replaced by an ad. I have the Adblock on, and it blocks everything else but on the shorts tab/feed.

### Steps to reproduce the issue

1. Press on the shorts
2. Scroll for a bit 
3. Encounter an ad
![IMG_1647](https://github.com/user-attachments/assets/23c4f9fa-9ed0-41b0-bfb7-d09476b29685)

### Are you using the newest version of uYouEnhanced?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Select the configuration used for building or obtaining the uYouEnhanced ipa. (Optional)

buildapp.yml (GitHub Actions — build method as suggested by [Wiki - Building](https://github.com/arichornlover/uYouEnhanced/wiki/Building))

**Comment by yodaluca23** [comment]
Related to #778
