### ISSUE TITLE
[Bug] error during compiling and packaging

### ISSUE THREAD

**Issue by Space-Trucker** [arichornlover/uYouEnhanced#810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the Wiki?

- [X] Yes, I have read the Wiki

### iOS/iPadOS version

IOS 17.3.1

### Device model

IPHONE 12 mini

### Sideload method

Feather

### Tweak version

uYouEnhanced_19.26.5-3.0.4

### Do you use YouTube Premium?

❌ No, I don't use YouTube Premium

### Describe the bug

Error during compiling and packaging, it gives me this while compiling during workflow running with ios 17.3.1 sdk. Everthing goes smooth unil this point.
![Capture](https://github.com/user-attachments/assets/07a3719a-fce6-4e99-b6df-bef46a80a242)

### Steps to reproduce the issue

1. Run the build worflow with ios 17.3.1 sdk
2. 
3. 
![Capture](https://github.com/user-attachments/assets/067a7a5d-48ed-4d23-aacc-629377670181)

### Are you using the newest version of uYouEnhanced?

✅ Yes, I'm using the latest version

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Select the configuration used for building or obtaining the uYouEnhanced ipa. (Optional)

buildapp.yml (GitHub Actions — build method as suggested by [Wiki - Building](https://github.com/arichornlover/uYouEnhanced/wiki/Building))

**Comment by Chippel** [comment]
Same here. Can not compile. 19.49.5

**Comment by jakest** [comment]
Also getting the same thing.

**Comment by jakest** [comment]
Got a bit further, but now I'm hitting this on the Create Release stage:
> Error: Request body length does not match content-length header

**Comment by jakest** [comment]
@arichornlover that worked. Thank you!

**Comment by Chippel** [comment]
I can now also confirm that I am able to compile the latest app successfully

**Comment by Space-Trucker** [comment]
> 17.3.1

Thanks, it worked! :)
